package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"profile-service/graph/generated"
	"profile-service/graph/model"
	"profile-service/internal/mapper"
	"profile-service/internal/models"
	"profile-service/pkg/middleware"

	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	userId, err := middleware.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unautorized: %w", err)
	}

	var existing models.User
	if err := r.DB.First(&existing, "id = ?", userId).Error; err == nil {
		return nil, fmt.Errorf("user already exists")
	}

	user := &models.User{
		ID:             uuid.MustParse(userId),
		Nickname:       input.Nickname,
		Email:          input.Email,
		ProfilePicture: input.ProfilePicture,
		Description:    input.Description,
		UserRating:     0,
	}

	if err := r.DB.Create(user).Error; err != nil {
		return nil, err
	}

	return mapper.MapUserToGraphQL(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	if input.Nickname != nil {
		user.Nickname = *input.Nickname
	}
	if input.Email != nil {
		user.Email = *input.Email
	}
	if input.ProfilePicture != nil {
		user.ProfilePicture = input.ProfilePicture
	}
	if input.Description != nil {
		user.Description = input.Description
	}

	if err := r.DB.Save(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return mapper.MapUserToGraphQL(&user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return false, fmt.Errorf("user not found: %w", err)
	}

	if err := r.DB.Delete(&user).Error; err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	return true, nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	if userID == followerID {
		return false, fmt.Errorf("cannot follow yourself")
	}

	var existing models.Follower
	if err := r.DB.First(&existing, "user_id = ? AND follower_id = ?", userID, followerID).Error; err == nil {
		return false, fmt.Errorf("user %s already following %s", userID, followerID)
	}

	follow := &models.Follower{
		UserID:     uuid.MustParse(userID),
		FollowerID: uuid.MustParse(followerID),
	}

	if err := r.DB.Create(follow).Error; err != nil {
		return false, fmt.Errorf("failed to follow: %w ", err)
	}

	return true, nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	var follow models.Follower
	if err := r.DB.First(&follow, "user_id = ? AND follower_id = ?", userID, followerID).Error; err != nil {
		return false, fmt.Errorf("user %s dont following %s", userID, followerID)
	}

	if err := r.DB.Delete(&follow).Error; err != nil {
		return false, fmt.Errorf("failed to unfollow: %w", err)
	}

	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	group := &models.Group{}

	if err := r.DB.Create(group).Error; err != nil {
		return nil, fmt.Errorf("failed to create group: %w", err)
	}

	var members []models.Member
	for _, userIDStr := range input.MemberIds {
		userID, err := uuid.Parse(userIDStr)
		if err != nil {
			return nil, fmt.Errorf("invalid user ID: %s", userIDStr)
		}

		member := models.Member{
			UserID:  userID,
			GroupID: group.ID,
		}

		if err := r.DB.Create(&member).Error; err != nil {
			return nil, fmt.Errorf("failed to add user %s to group: %w", userIDStr, err)
		}

		members = append(members, member)
	}

	for i := range members {
		if err := r.DB.First(&members[i].User, "id = ?", members[i].UserID).Error; err != nil {
			return nil, fmt.Errorf("failed to load user %s: %w", members[i].UserID, err)
		}
	}

	return mapper.MapGroupToGraphQL(group, members), nil
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var existing models.Member
	if err := r.DB.First(&existing, "user_id = ? AND group_id = ?", userID, groupID).Error; err == nil {
		return false, fmt.Errorf("user already in the group")
	}

	member := &models.Member{
		UserID:  uuid.MustParse(userID),
		GroupID: uuid.MustParse(groupID),
	}

	if err := r.DB.Create(member).Error; err != nil {
		return false, fmt.Errorf("failed to add user to group: %w", err)
	}

	return true, nil
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var membership models.Member
	if err := r.DB.First(&membership, "user_id = ? AND group_id = ?", userID, groupID).Error; err != nil {
		return false, fmt.Errorf("user %s not in group %s", userID, groupID)
	}

	if err := r.DB.Delete(&membership).Error; err != nil {
		return false, fmt.Errorf("failed to remove user from group: %w", err)
	}

	return true, nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	var group models.Group
	if err := r.DB.First(&group, "id = ?", id).Error; err != nil {
		return false, fmt.Errorf("group not found: %w", err)
	}

	if err := r.DB.Delete(&group).Error; err != nil {
		return false, fmt.Errorf("failed to delete group: %w", err)
	}

	return true, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
