package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"profile-service/graph/generated"
	"profile-service/graph/model"
	"profile-service/internal/mapper"
	"profile-service/internal/models"

	"github.com/google/uuid"
)

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, userID string) (*model.User, error) {
	var user models.User

	uid, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("unautorized (incorrect id): %w", err)
	}

	if user, err = r.UserRepo.GetUserByID(ctx, uid); err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, uid); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, uid); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByNickname is the resolver for the userByNickname field.
func (r *queryResolver) UserByNickname(ctx context.Context, nickname string) (*model.User, error) {
	var user models.User
	var err error
	if user, err = r.UserRepo.GetUserByNickname(ctx, nickname); err != nil {
		return nil, fmt.Errorf("user not found with nickname %s: %w", nickname, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	var user models.User
	var err error
	if user, err = r.UserRepo.GetUserByEmail(ctx, email); err != nil {
		return nil, fmt.Errorf("user not found with email %s: %w", email, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// FollowersOf is the resolver for the followersOf field.
func (r *queryResolver) FollowersOf(ctx context.Context, userID string) ([]*model.User, error) {
	var followerLinks []models.Follower
	userIDuuid, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("user not found (incorrect id): %w", err)
	}

	if followerLinks, err = r.UserRepo.GetFollowers(ctx, userIDuuid); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	return followers, nil
}

// FollowingOf is the resolver for the followingOf field.
func (r *queryResolver) FollowingOf(ctx context.Context, userID string) ([]*model.User, error) {
	userIDuuid, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("user not found (incorrect id): %w", err)
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, userIDuuid); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	return following, nil
}

// FollowersCount is the resolver for the followersCount field.
func (r *queryResolver) FollowersCount(ctx context.Context, userID string) (int, error) {
	panic(fmt.Errorf("not implemented: FollowersCount - followersCount"))
}

// FollowingCount is the resolver for the followingCount field.
func (r *queryResolver) FollowingCount(ctx context.Context, userID string) (int, error) {
	panic(fmt.Errorf("not implemented: FollowingCount - followingCount"))
}

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, groupID string) ([]*model.User, error) {
	id, err := uuid.Parse(groupID)
	if err != nil {
		return nil, fmt.Errorf("user not found (incorrect id): %w", err)
	}

	if _, err = r.UserRepo.GetGroupByID(ctx, id); err != nil {
		return nil, fmt.Errorf("group not found with id %s: %w", id, err)
	}

	var members []models.Member
	if members, err = r.UserRepo.GetMembers(ctx, id); err != nil {
		return nil, fmt.Errorf("failed to load members for group %s: %w", id, err)
	}

	var users []*model.User
	for _, member := range members {
		var user models.User
		if user, err = r.UserRepo.GetUserByID(ctx, member.UserID); err != nil {
			return nil, fmt.Errorf("failed to load user for member %v: %w", member.UserID, err)
		}
		users = append(users, mapper.MapUserToGraphQL(&user))
	}

	return users, nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	userIDuuid, err := uuid.Parse(userID)
	if err != nil {
		return false, fmt.Errorf("user not found (incorrect id): %w", err)
	}
	groupIDuuid, err := uuid.Parse(groupID)
	if err != nil {
		return false, fmt.Errorf("group not found (incorrect id): %w", err)
	}

	if _, err := r.UserRepo.GetMember(ctx, userIDuuid, groupIDuuid); err != nil {
		return false, fmt.Errorf("failed to check if user is in group: %w", err)
	}

	return true, nil
}

// GroupsOfUser is the resolver for the groupsOfUser field.
func (r *queryResolver) GroupsOfUser(ctx context.Context, userID string) ([]*model.Group, error) {
	userIDuuid, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("user not found (incorrect id): %w", err)
	}

	var members []models.Member
	if members, err = r.UserRepo.GetGroups(ctx, userIDuuid); err != nil {
		return nil, fmt.Errorf("failed to find groups for user: %w", err)
	}

	var groups []*model.Group
	for _, member := range members {
		var group models.Group
		if group, err = r.UserRepo.GetGroupByID(ctx, member.GroupID); err != nil {
			return nil, fmt.Errorf("failed to find group: %w", err)
		}

		groups = append(groups, mapper.MapGroupToGraphQL(&group, members))
	}

	return groups, nil
}

// RequestJoinGroup is the resolver for the requestJoinGroup field.
func (r *queryResolver) RequestJoinGroup(ctx context.Context, groupID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestJoinGroup - requestJoinGroup"))
}

// AcceptJoinToGroup is the resolver for the acceptJoinToGroup field.
func (r *queryResolver) AcceptJoinToGroup(ctx context.Context, requestID string) (bool, error) {
	panic(fmt.Errorf("not implemented: AcceptJoinToGroup - acceptJoinToGroup"))
}

// GetSettingsStatuses is the resolver for the getSettingsStatuses field.
func (r *queryResolver) GetSettingsStatuses(ctx context.Context) ([]*model.SettingsStatuses, error) {
	panic(fmt.Errorf("not implemented: GetSettingsStatuses - getSettingsStatuses"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
