package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"profile-service/graph/generated"
	"profile-service/graph/model"
	"profile-service/internal/mapper"
	"profile-service/internal/models"
)

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", id).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", link.FollowerID).Error; err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", id).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", link.UserID).Error; err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByNickname is the resolver for the userByNickname field.
func (r *queryResolver) UserByNickname(ctx context.Context, nickname string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "nickname = ?", nickname).Error; err != nil {
		return nil, fmt.Errorf("user not found with nickname %s: %w", nickname, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", user.ID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", user.ID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	result := mapper.MapUserToGraphQL(&user)
	result.Followers = followers
	result.Following = following

	return result, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "email = ?", email).Error; err != nil {
		return nil, fmt.Errorf("user not found with email %s: %w", email, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", user.ID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", user.ID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	result := mapper.MapUserToGraphQL(&user)
	result.Followers = followers
	result.Following = following

	return result, nil
}

// FollowersOf is the resolver for the followersOf field.
func (r *queryResolver) FollowersOf(ctx context.Context, userID string) ([]*model.User, error) {
	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", userID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	return followers, nil
}

// FollowingOf is the resolver for the followingOf field.
func (r *queryResolver) FollowingOf(ctx context.Context, userID string) ([]*model.User, error) {
	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", userID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	return following, nil
}

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, id string) ([]*model.User, error) {
	var group models.Group
	if err := r.DB.First(&group, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("group not found with id %s: %w", id, err)
	}

	var members []models.Member
	if err := r.DB.Where("group_id = ?", id).Find(&members).Error; err != nil {
		return nil, fmt.Errorf("failed to load members for group %s: %w", id, err)
	}

	var users []*model.User
	for _, member := range members {
		var user models.User
		if err := r.DB.First(&user, "id = ?", member.UserID).Error; err != nil {
			return nil, fmt.Errorf("failed to load user for member %v: %w", member.UserID, err)
		}
		users = append(users, mapper.MapUserToGraphQL(&user))
	}

	return users, nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var member models.Member
	if err := r.DB.First(&member, "user_id = ? AND group_id = ?", userID, groupID).Error; err != nil {
		return false, fmt.Errorf("failed to check if user is in group: %w", err)
	}

	return true, nil
}

// GroupsOfUser is the resolver for the groupsOfUser field.
func (r *queryResolver) GroupsOfUser(ctx context.Context, userID string) ([]*model.Group, error) {
	var members []models.Member
	if err := r.DB.Where("user_id = ?", userID).Find(&members).Error; err != nil {
		return nil, fmt.Errorf("failed to find groups for user: %w", err)
	}

	var groups []*model.Group
	for _, member := range members {
		var group models.Group
		if err := r.DB.First(&group, "id = ?", member.GroupID).Error; err != nil {
			return nil, fmt.Errorf("failed to find group: %w", err)
		}

		groups = append(groups, mapper.MapGroupToGraphQL(&group, members))
	}

	return groups, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
