package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"profile-service/graph/generated"
	"profile-service/graph/model"
	"profile-service/internal/mapper"
	"profile-service/internal/models"

	"github.com/google/uuid"
)

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, userID uuid.UUID) (*model.User, error) {
	var user models.User

	user, err := r.UserRepo.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, userID); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, userID); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByNickname is the resolver for the userByNickname field.
func (r *queryResolver) UserByNickname(ctx context.Context, nickname string) (*model.User, error) {
	var user models.User
	var err error
	if user, err = r.UserRepo.GetUserByNickname(ctx, nickname); err != nil {
		return nil, fmt.Errorf("user not found with nickname %s: %w", nickname, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	var user models.User
	var err error
	if user, err = r.UserRepo.GetUserByEmail(ctx, email); err != nil {
		return nil, fmt.Errorf("user not found with email %s: %w", email, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if followerLinks, err = r.UserRepo.GetFollowers(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if followingLinks, err = r.UserRepo.GetFollowings(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	res := mapper.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// FollowersOf is the resolver for the followersOf field.
func (r *queryResolver) FollowersOf(ctx context.Context, userID uuid.UUID) ([]*model.User, error) {
	var followerLinks []models.Follower
	followerLinks, err := r.UserRepo.GetFollowers(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.FollowerID); err == nil {
			followers = append(followers, mapper.MapUserToGraphQL(&u))
		}
	}

	return followers, nil
}

// FollowingOf is the resolver for the followingOf field.
func (r *queryResolver) FollowingOf(ctx context.Context, userID uuid.UUID) ([]*model.User, error) {
	var followingLinks []models.Follower
	followingLinks, err := r.UserRepo.GetFollowings(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if u, err = r.UserRepo.GetUserByID(ctx, link.UserID); err == nil {
			following = append(following, mapper.MapUserToGraphQL(&u))
		}
	}

	return following, nil
}

// FollowersCount is the resolver for the followersCount field.
func (r *queryResolver) FollowersCount(ctx context.Context, userID uuid.UUID) (int, error) {
	var followerLinks []models.Follower
	followerLinks, err := r.UserRepo.GetFollowers(ctx, userID)
	if err != nil {
		return 0, fmt.Errorf("failed to load followers: %w", err)
	}

	return len(followerLinks), nil
}

// FollowingCount is the resolver for the followingCount field.
func (r *queryResolver) FollowingCount(ctx context.Context, userID uuid.UUID) (int, error) {
	var followingLinks []models.Follower
	followingLinks, err := r.UserRepo.GetFollowings(ctx, userID)
	if err != nil {
		return 0, fmt.Errorf("failed to load following: %w", err)
	}

	return len(followingLinks), nil
}

// GetSettingsStatuses is the resolver for the getSettingsStatuses field.
func (r *queryResolver) GetSettingsStatuses(ctx context.Context) ([]*model.SettingsStatuses, error) {
	panic(fmt.Errorf("not implemented: GetSettingsStatuses - getSettingsStatuses"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
