FROM debian:stable-slim AS installer
ARG version=v0.36.2

RUN apt update && apt install -y curl

RUN curl -sSL https://rover.apollo.dev/nix/${version} | sh

FROM debian:stable-slim AS runner

COPY --from=installer /root/.rover/bin/rover /root/.rover/bin/rover
ENV PATH="/root/.rover/bin:${PATH}"

RUN apt update && apt install -y ca-certificates && rm -rf /var/lib/apt/lists/* && apt-get clean

#ENTRYPOINT [ "/root/.rover/bin/rover" ]