supergraph:
  listen: 0.0.0.0:4000
  path: /
  introspection: true

sandbox:
  enabled: true

homepage:
  enabled: false

health_check:
  listen: 0.0.0.0:8088
  enabled: true
  path: /health

telemetry:
  exporters:
    logging:
      common:
        service_name: "apollo-router"
