// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AddCommentInput struct {
	PinID   uuid.UUID `json:"pinId"`
	UserID  uuid.UUID `json:"userId"`
	Content string    `json:"content"`
}

type AddImageInput struct {
	PinID       uuid.UUID `json:"pinId"`
	ImageURL    string    `json:"imageUrl"`
	OrderNumber int       `json:"orderNumber"`
}

type Board struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	AccessLevel AccessLevelType `json:"accessLevel"`
	OwnerID     uuid.UUID       `json:"ownerId"`
	OwnerType   OwnerType       `json:"ownerType"`
	CreatedAt   time.Time       `json:"createdAt"`
	Pins        []*Pin          `json:"pins,omitempty"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Author    *User     `json:"author"`
}

type CreateBoardInput struct {
	Name        string          `json:"name"`
	AccessLevel AccessLevelType `json:"accessLevel"`
	OwnerID     uuid.UUID       `json:"ownerId"`
	OwnerType   OwnerType       `json:"ownerType"`
}

type CreateGroupInput struct {
	Members []uuid.UUID `json:"members"`
}

type CreatePinInput struct {
	Name        string    `json:"name"`
	OwnerID     uuid.UUID `json:"ownerId"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
	Description *string   `json:"description,omitempty"`
}

type Group struct {
	ID      uuid.UUID `json:"id"`
	Members []*User   `json:"members"`
}

type Mutation struct {
}

type Pin struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Owner       *User       `json:"owner"`
	Address     *string     `json:"address,omitempty"`
	Latitude    float64     `json:"latitude"`
	Longitude   float64     `json:"longitude"`
	Description *string     `json:"description,omitempty"`
	Rating      float64     `json:"rating"`
	CreatedAt   time.Time   `json:"createdAt"`
	Images      []*PinImage `json:"images,omitempty"`
	Comments    []*Comment  `json:"comments,omitempty"`
}

func (Pin) IsEntity() {}

type PinImage struct {
	ID          uuid.UUID `json:"id"`
	OrderNumber int       `json:"orderNumber"`
	ImageURL    string    `json:"imageUrl"`
}

type Query struct {
}

type UpdateBoardInput struct {
	Name        *string          `json:"name,omitempty"`
	AccessLevel *AccessLevelType `json:"accessLevel,omitempty"`
	UserID      uuid.UUID        `json:"userId"`
}

type UpdatePinInput struct {
	Name        *string   `json:"name,omitempty"`
	Latitude    *float64  `json:"latitude,omitempty"`
	Longitude   *float64  `json:"longitude,omitempty"`
	Description *string   `json:"description,omitempty"`
	Rating      *float64  `json:"rating,omitempty"`
	UserID      uuid.UUID `json:"userId"`
}

type User struct {
	ID uuid.UUID `json:"id"`
}

func (User) IsEntity() {}

type AccessLevelType string

const (
	AccessLevelTypePrivate     AccessLevelType = "private"
	AccessLevelTypePublic      AccessLevelType = "public"
	AccessLevelTypeGroup       AccessLevelType = "group"
	AccessLevelTypeGroupPublic AccessLevelType = "group_public"
)

var AllAccessLevelType = []AccessLevelType{
	AccessLevelTypePrivate,
	AccessLevelTypePublic,
	AccessLevelTypeGroup,
	AccessLevelTypeGroupPublic,
}

func (e AccessLevelType) IsValid() bool {
	switch e {
	case AccessLevelTypePrivate, AccessLevelTypePublic, AccessLevelTypeGroup, AccessLevelTypeGroupPublic:
		return true
	}
	return false
}

func (e AccessLevelType) String() string {
	return string(e)
}

func (e *AccessLevelType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessLevelType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessLevelType", str)
	}
	return nil
}

func (e AccessLevelType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessLevelType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessLevelType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OwnerType string

const (
	OwnerTypeUser  OwnerType = "user"
	OwnerTypeGroup OwnerType = "group"
)

var AllOwnerType = []OwnerType{
	OwnerTypeUser,
	OwnerTypeGroup,
}

func (e OwnerType) IsValid() bool {
	switch e {
	case OwnerTypeUser, OwnerTypeGroup:
		return true
	}
	return false
}

func (e OwnerType) String() string {
	return string(e)
}

func (e *OwnerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OwnerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OwnerType", str)
	}
	return nil
}

func (e OwnerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OwnerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OwnerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
