// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type AccessLevel struct {
	ID   uuid.UUID `json:"id"`
	Type string    `json:"type"`
}

type AddCommentInput struct {
	PinID   uuid.UUID `json:"pinId"`
	UserID  uuid.UUID `json:"userId"`
	Content string    `json:"content"`
}

type AddImageInput struct {
	PinID       uuid.UUID `json:"pinId"`
	ImageURL    string    `json:"imageUrl"`
	OrderNumber int       `json:"orderNumber"`
}

type Board struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	AccessLevel *AccessLevel `json:"accessLevel"`
	GroupID     *Group       `json:"groupId"`
	CreatedAt   time.Time    `json:"createdAt"`
	Pins        []*Pin       `json:"pins,omitempty"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Author    *User     `json:"author"`
}

type CreateBoardInput struct {
	Name          string    `json:"name"`
	AccessLevelID uuid.UUID `json:"accessLevelId"`
	GroupID       uuid.UUID `json:"groupId"`
}

type CreatePinInput struct {
	Name        string    `json:"name"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
	Description *string   `json:"description,omitempty"`
	OwnerID     uuid.UUID `json:"ownerId"`
}

type Group struct {
	ID uuid.UUID `json:"id"`
}

func (Group) IsEntity() {}

type Mutation struct {
}

type Pin struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Latitude    float64     `json:"latitude"`
	Longitude   float64     `json:"longitude"`
	Description *string     `json:"description,omitempty"`
	Owner       *User       `json:"owner"`
	Rating      float64     `json:"rating"`
	CreatedAt   time.Time   `json:"createdAt"`
	Images      []*PinImage `json:"images,omitempty"`
	Comments    []*Comment  `json:"comments,omitempty"`
}

type PinImage struct {
	ID          uuid.UUID `json:"id"`
	OrderNumber int       `json:"orderNumber"`
	ImageURL    string    `json:"imageUrl"`
}

type Query struct {
}

type UpdateBoardInput struct {
	Name          *string    `json:"name,omitempty"`
	AccessLevelID *uuid.UUID `json:"accessLevelId,omitempty"`
	UserID        uuid.UUID  `json:"userId"`
}

type UpdatePinInput struct {
	Name        *string   `json:"name,omitempty"`
	Latitude    *float64  `json:"latitude,omitempty"`
	Longitude   *float64  `json:"longitude,omitempty"`
	Description *string   `json:"description,omitempty"`
	Rating      *float64  `json:"rating,omitempty"`
	UserID      uuid.UUID `json:"userId"`
}

type User struct {
	ID uuid.UUID `json:"id"`
}

func (User) IsEntity() {}
