input CreateUserInput {
  nickname: String!
  email: String!
  nick_tag: String!
  profilePicture: String
  description: String
}

input UpdateUserInput {
  nickname: String
  email: String
  nick_tag: String!
  profilePicture: String
  description: String
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(userId: UUID!, input: UpdateUserInput!): User!
  deleteUser(userId: UUID!): Boolean!

  followUser(userId: UUID!, followerId: UUID!): Boolean!
  unfollowUser(userId: UUID!, followerId: UUID!): Boolean!

  changeAccessBookmarks(userId: UUID!, newStatus: UUID!): Boolean!
}

scalar UUID

enum UserStatus {
  active
  deleted
}

type User @key(fields: "id") {
  id: UUID!
  nickname: String!
  email: String!
  nickTag: String!
  profilePicture: String
  description: String
  status: UserStatus!
  userRating: Float!
  followers: [User!]!
  following: [User!]!
}

type SettingsStatuses {
  id: UUID!
  type: String!
  description: String
}

type Query {
  userById(userId: UUID!): User
  userByNickname(nickname: String!): User
  userByEmail(email: String!): User

  followersOf(userId: UUID!): [User!]!
  followingOf(userId: UUID!): [User!]!
  followersCount(userId: UUID!): Int!
  followingCount(userId: UUID!): Int!

  getSettingsStatuses: [SettingsStatuses!]!
}

