apiVersion: v1
kind: Service
metadata:
  name: {{ include "content-db.fullname" . }}-headless
  labels:
    {{- include "content-db.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "content-db.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
