federation_version: 2.5
subgraphs:
  feed-service:
    routing_url: http://feed-service:8080
    schema:
      subgraph_url: http://feed-service:8080
  profile-service:
    routing_url: http://profile-service:8080
    schema:
      subgraph_url: http://profile-service:8080