package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"encoding/json"
	"feed-service/graph/generated"
	"feed-service/graph/model"

	"github.com/google/uuid"
)

// SearchPins is the resolver for the searchPins field.
func (r *queryResolver) SearchPins(ctx context.Context, query string) ([]*model.Pin, error) {
	searchQuery := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
				"must": []interface{}{
					map[string]interface{}{
						"multi_match": map[string]interface{}{
							"query":     query,
							"fields":    []string{"name^2", "description", "place_name", "place_purpose_name", "place_type"},
							"fuzziness": "AUTO",
						},
					},
				},
				"filter": []interface{}{
					map[string]interface{}{
						"term": map[string]interface{}{
							"access_level": "public",
						},
					},
				},
			},
		},
		"size": 20,
	}

	raw, err := r.OSClient.Search(ctx, "pins-*", searchQuery)
	if err != nil {
		return nil, err
	}

	var pins []*model.Pin
	for _, src := range raw {
		var p model.Pin
		if err := json.Unmarshal(src, &p); err == nil {
			pins = append(pins, &p)
		}
	}

	return pins, nil
}

// SearchBoards is the resolver for the searchBoards field.
func (r *queryResolver) SearchBoards(ctx context.Context, query string) ([]*model.Board, error) {
	searchQuery := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
				"must": []interface{}{
					map[string]interface{}{
						"multi_match": map[string]interface{}{
							"query":     query,
							"fields":    []string{"name"},
							"fuzziness": "AUTO",
						},
					},
				},
				"filter": []interface{}{
					map[string]interface{}{
						"term": map[string]interface{}{
							"access_level": "public",
						},
					},
				},
			},
		},
		"size": 20,
	}

	raw, err := r.OSClient.Search(ctx, "boards-*", searchQuery)
	if err != nil {
		return nil, err
	}

	var boards []*model.Board
	for _, src := range raw {
		var b model.Board
		if err := json.Unmarshal(src, &b); err == nil {
			boards = append(boards, &b)
		}
	}

	return boards, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string) ([]*model.User, error) {
	searchQuery := map[string]interface{}{
		"query": map[string]interface{}{
			"multi_match": map[string]interface{}{
				"query":     query,
				"fields":    []string{"nickname", "nick_tag", "description", "email"},
				"fuzziness": "AUTO",
			},
		},
		"size": 20,
	}

	raw, err := r.OSClient.Search(ctx, "users-*", searchQuery)
	if err != nil {
		return nil, err
	}

	var users []*model.User
	for _, src := range raw {
		var u model.User
		if err := json.Unmarshal(src, &u); err == nil {
			users = append(users, &u)
		}
	}

	return users, nil
}

// FeedPins is the resolver for the feedPins field.
func (r *queryResolver) FeedPins(ctx context.Context, userID uuid.UUID) ([]*model.Pin, error) {
	searchQuery := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
				"must": []map[string]interface{}{
					{"term": map[string]interface{}{"access_level": "public"}},
				},
			},
		},
		"sort": []map[string]interface{}{
			{"likes_count": map[string]interface{}{"order": "desc"}},
			{"created_at": map[string]interface{}{"order": "desc"}},
		},
		"size": 30,
	}

	raw, err := r.OSClient.Search(ctx, "pins-*", searchQuery)
	if err != nil {
		return nil, err
	}

	var pins []*model.Pin
	for _, src := range raw {
		var p model.Pin
		if err := json.Unmarshal(src, &p); err == nil {
			pins = append(pins, &p)
		}
	}

	return pins, nil
}

// FeedBoards is the resolver for the feedBoards field.
func (r *queryResolver) FeedBoards(ctx context.Context, userID uuid.UUID) ([]*model.Board, error) {
	searchQuery := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
				"must": []map[string]interface{}{
					{"term": map[string]interface{}{"access_level": "public"}},
				},
			},
		},
		"sort": []map[string]interface{}{
			{"likes_count": map[string]interface{}{"order": "desc"}},
			{"created_at": map[string]interface{}{"order": "desc"}},
		},
		"size": 30,
	}

	raw, err := r.OSClient.Search(ctx, "boards-*", searchQuery)
	if err != nil {
		return nil, err
	}

	var boards []*model.Board
	for _, src := range raw {
		var b model.Board
		if err := json.Unmarshal(src, &b); err == nil {
			boards = append(boards, &b)
		}
	}

	return boards, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
