package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"feed-service/graph/generated"
	"feed-service/graph/model"
)

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context) ([]*model.Pin, error) {
	return []*model.Pin{}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
