input CreateBoardInput {
  name: String!
  accessLevel: AccessLevelType!
  ownerId: UUID!
  ownerType: OwnerType!
}

input UpdateBoardInput {
  name: String
  accessLevel: AccessLevelType
  userId: UUID!
}

input CreatePinInput {
  name: String!
  ownerId: UUID!
  address String
  latitude: Float!
  longitude: Float!
  description: String
}

input UpdatePinInput {
  name: String
  latitude: Float
  longitude: Float
  description: String
  rating: Float
  userId: UUID!
}

input AddCommentInput {
  pinId: UUID!
  userId: UUID!
  content: String!
}

input AddImageInput {
  pinId: UUID!
  imageUrl: String!
  orderNumber: Int!
}

input CreateGroupInput {
  members: [UUID!]!
}

type Mutation {
  createBoard(input: CreateBoardInput!): Board!
  updateBoard(id: UUID!, input: UpdateBoardInput!): Board!

  createPin(input: CreatePinInput!): Pin!
  updatePin(id: UUID!, input: UpdatePinInput!): Pin!

  addPinToBoard(pinId: UUID!, boardId: UUID!): Board!
  removePinFromBoard(pinId: UUID!, boardId: UUID!): Board!

  addCommentToPin(input: AddCommentInput!): Comment!
  updateComment(id: UUID!, content: String!): Comment!
  deleteComment(id: UUID!): Boolean!

  addImageToPin(input: AddImageInput!): PinImage!
  removeImageFromPin(imageId: UUID!): Boolean!
  updateImageOrder(imageId: UUID!, newOrder: Int!): PinImage!

  createGroup(input: CreateGroupInput!): Group!
  addUserToGroup(userId: UUID!, groupId: UUID!): Boolean!
  removeUserFromGroup(userId: UUID!, groupId: UUID!): Boolean!
  deleteGroup(groupId: UUID!): Boolean!
  requestJoinGroup(groupId: UUID!, userId: UUID!): Boolean!
  acceptJoinToGroup(requestId: UUID!): Boolean!
}