input CreateBoardInput {
  name: String!
  accessLevel: AccessLevelType!
  ownerId: UUID!
  ownerType: OwnerType!
}

input UpdateBoardInput {
  name: String
  accessLevel: AccessLevelType
  userId: UUID!
}

input CreatePinInput {
  name: String!
  ownerId: UUID!
  latitude: Float!
  longitude: Float!
  description: String
}

input UpdatePinInput {
  name: String
  latitude: Float
  longitude: Float
  description: String
  rating: Float
  userId: UUID!
}

input AddCommentToPinInput {
  pinId: UUID!
  userId: UUID!
  message: String!
}

input AddCommentToBoardInput {
  boardId: UUID!
  userId: UUID!
  message: String!
}

input AddImageInput {
  pinId: UUID!
  imageUrl: String!
  orderNumber: Int!
}

input CreateGroupInput {
  members: [UUID!]!
}

type Mutation {
  createBoard(input: CreateBoardInput!): Board!
  updateBoard(id: UUID!, input: UpdateBoardInput!): Board!

  createPin(input: CreatePinInput!): Pin!
  updatePin(id: UUID!, input: UpdatePinInput!): Pin!

  addPinToBoard(pinId: UUID!, boardId: UUID!): Board!
  removePinFromBoard(pinId: UUID!, boardId: UUID!): Board!

  addImageToPin(input: AddImageInput!): PinImage!
  removeImageFromPin(imageId: UUID!): Boolean!
  updateImageOrder(imageId: UUID!, newOrder: Int!): PinImage!

  addCommentToPin(input: AddCommentToPinInput!): CommentToPin!
  updateCommentToPin(id: UUID!, message: String!): CommentToPin!
  deleteCommentToPin(id: UUID!): Boolean!

  addCommentToBoard(input: AddCommentToBoardInput!): CommentToBoard!
  updateCommentToBoard(id: UUID!, message: String!): CommentToBoard!
  deleteCommentToBoard(id: UUID!): Boolean!

  createGroup(input: CreateGroupInput!): Group!
  addUserToGroup(userId: UUID!, groupId: UUID!): Boolean!
  removeUserFromGroup(userId: UUID!, groupId: UUID!): Boolean!
  deleteGroup(groupId: UUID!): Boolean!
  requestJoinGroup(groupId: UUID!, userId: UUID!): Boolean!
  acceptJoinToGroup(requestId: UUID!): Boolean!

  reactionToPin(pinId: UUID!, reactionId: UUID!, userId: UUID!): Boolean!
  reactionToBoard(boardId: UUID!, reactionId: UUID!, userId: UUID!): Boolean!

  bookmarkToPin(pinId: UUID!, userId: UUID!): Boolean!
  bookmarkToBoard(boardId: UUID!, userId: UUID!): Boolean!
}

