type Pin @key(fields: "id") {
  id: UUID!
  name: String!
  owner: User!
  address: String
  latitude: Float!
  longitude: Float!
  description: String
  rating: Float!
  createdAt: Time!

  place: Place
  images: [PinImage!]
  # comments: [Comment!]
}

type PinImage {
  id: UUID!
  orderNumber: Int!
  imageUrl: String!
}

type CommentToPin {
  id: UUID!
  pinId: UUID!
  message: String!
  createdAt: Time!
  owner: User!
}

type Place {
  id: UUID!
  gis_id: UUID
  name: String!
  address: String
  latitude: Float!
  longitude: Float!
  purpose_name: String
  type: String
}