type Query {
  # Поиск доски
    # ИЗМЕНЕНО:
    # - добавлена опциональная загрузка Пинов
  board(id: UUID!): Board
    # ИЗМЕНЕНО
    # Если "board(id: UUID!): Board" работает, то нужно добавить опциональную загрузку Пинов
  boardByName(name: String!): [Board!]
    # ИЗМЕНЕНО
    # Если "board(id: UUID!): Board" работает, то нужно добавить опциональную загрузку Пинов
  boardsByGroup(groupId: UUID!): [Board!]

  # Поиск пина
  pin(id: UUID!): Pin
  pinsByUser(userId: UUID!): [Pin!]
  pinsByName(name: String!): [Pin!]
  pinsByLocation(query: String!): [Pin!]

  groupById(groupId: UUID!): [User!]
  isUserInGroup(userId: UUID!, groupId: UUID!): Boolean!
  groupsOfUser(userId: UUID!): [Group!]!
}