type Query {
  # Поиск доски
    # Переписано, нужно потестить
    # - надо проверить опциональную Пинов
  board(id: UUID!): Board
    # Переписано, нужно потестить
    # Если board работает, то добавить сюда опциональную загрузку Пинов
  boardByName(name: String!): [Board!]
    # Переписано, нужно потестить
    # Если board работает, то добавить сюда опциональную загрузку Пинов
  boardsByGroup(groupId: UUID!): [Board!]

  # Поиск пина
  pin(id: UUID!): Pin
  pinsByUser(userId: UUID!): [Pin!]
  pinsByName(name: String!): [Pin!]
  pinsByLocation(query: String!): [Pin!]
}