type Query {
  board(id: UUID!): Board
  boardByName(name: String!, limit: Int = 10, offset: Int = 0): [Board!]
  boardsByGroup(groupId: UUID!, limit: Int = 10, offset: Int = 0): [Board!]

  pin(id: UUID!): Pin
  pinsByUser(userId: UUID!, limit: Int = 10, offset: Int = 0): [Pin!]
  pinsByName(name: String!, limit: Int = 10, offset: Int = 0): [Pin!]
  pinsByLocation(query: String!, limit: Int = 10, offset: Int = 0): [Pin!]

  groupById(groupId: UUID!): Group
  isUserInGroup(userId: UUID!, groupId: UUID!): Boolean!
  groupsOfUser(userId: UUID!, limit: Int = 10, offset: Int = 0): [Group!]!

  commentsByBoard(boardId: UUID!, limit: Int = 10, offset: Int = 0): [CommentToBoard]!
  commentsByPin(pinId: UUID!, limit: Int = 10, offset: Int = 0): [CommentToPin]!

  ownBoardsByUser(userId: UUID!): [Board!]!
  groupBoardsByUser(userId: UUID!): [Board!]!
  countOwnBoardsByUser(userId: UUID!): Int!
  countGroupBoardsByUser(userId: UUID!): Int!

  reactions: [Reaction!]!
  countAllReactionsToPin(pinId: UUID!): Int!
  countAllReactionsToBoard(boardId: UUID!): Int!
}

