server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    d.zhdanov.ccfit.nsu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      global cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: public
          uri: http://localhost:8081
          predicates:
            - Path=/public/**
          filters: [ ]

        - id: authorized
          uri: http://localhost:8081
          predicates:
            - Path=/authorized/**
          filters:
            - AddUserInfoHeader

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_SET_URI}