apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      name: java-service
      labels:
        app: java-service
    spec:
      containers:
        - name: java-service
          image: java-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
      