services:
  content-db:
    image: postgres:15
    container_name: content_db
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB:-content}
    ports:
      - "5435:5432"
    volumes:
      - content_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d content"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  content-migrator:
    build:
      context: ../database/content-service
      dockerfile: Dockerfile.migrator
    depends_on:
      content-db:
        condition: service_healthy
    networks:
      - app-network
    entrypoint:
      [
        "migrate",
        "-path=/app/migrations",
        "-database=postgres://user:pass@content-db:5432/content?sslmode=disable",
        "up"
      ]

  feed-db:
    image: postgres:15
    container_name: feed_db
    ports:
      - "5436:5432"
    volumes:
      - feed_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d feed" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  feed-migrator:
    build:
      context: ../database/feed-service
      dockerfile: Dockerfile.migrator
    depends_on:
      feed-db:
        condition: service_healthy
    networks:
      - app-network
    entrypoint:
      [
        "migrate",
        "-path=/app/migrations",
        "-database=postgres://user:pass@feed-db:5432/feed?sslmode=disable",
        "up"
      ]
  
  profile-db:
    image: postgres:15
    container_name: profile_db
    environment:
      POSTGRES_USER: ${PROFILE_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${PROFILE_POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${PROFILE_POSTGRES_DB:-profile}
    ports:
      - "5437:5432"
    volumes:
      - profile_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d profile"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  profile-migrator:
    build:
      context: ../database/profile-service
      dockerfile: Dockerfile.migrator
    depends_on:
      profile-db:
        condition: service_healthy
    networks:
      - app-network
    entrypoint:
      [
        "migrate",
        "-path=/app/migrations",
        "-database=postgres://user:pass@profile-db:5432/profile?sslmode=disable",
        "up"
      ]

  profile-service:
    build:
      context: ../backend/profile-service
      dockerfile: Dockerfile
    container_name: profile-service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PROFILE_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${PROFILE_POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${PROFILE_POSTGRES_DB:-profile}
      POSTGRES_HOST: ${CONTENT_POSTGRES_HOST:-profile-db}
      PORT: ${CONTENT_PORT:-8080}
    depends_on:
      profile-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  content-service:
    build:
      context: ../backend/content-service
      dockerfile: Dockerfile
    container_name: content-service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB:-content_db}
      POSTGRES_HOST: ${CONTENT_POSTGRES_HOST:-content-db}
      DB_PORT: ${CONTENT_DB_PORT:-5432}
      PORT: ${CONTENT_PORT:-8080}
    depends_on:
      content-db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - app-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
#      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
#      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_POSTGRES_URL}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    # - ./keycloak/data:/opt/keycloak/data/export
    networks:
      - app-network
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak_postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "keycloak" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
  geo-api:
    build:
      context: ../backend/geo-api
      dockerfile: Dockerfile
    container_name: geo-api
    environment:
      GEO_API_URL: ${GEO_API_URL:-https://geocode-maps.yandex.ru/v1}
      GEO_API_KEY: ${GEO_API_KEY:-}
    working_dir: /app
    ports:
      - "15000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider --quiet http://localhost:8000/actuator/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rover:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    container_name: rover-cli
    volumes:
      - ./apollo:/etc/apollo/router:ro
      - rover_data:/etc/apollo/rover
    working_dir: /app
    command: supergraph compose --config /etc/apollo/router/supergraph-config.yaml --output /etc/apollo/rover/supergraph-schema.graphql --log=debug
    depends_on:
      geo-api:
        condition: service_healthy
    networks:
      - app-network

  router:
    image: ghcr.io/apollographql/router:v2.2.1
    container_name: apollo-router
    ports:
      - "14000:4000"
    volumes:
      - rover_data:/etc/apollo/rover
      - ./apollo/router.yaml:/ect/config/router.yaml:ro
    command: --supergraph /etc/apollo/rover/supergraph-schema.graphql --config /ect/config/router.yaml
    depends_on:
      - geo-api
    networks:
      - app-network

volumes:
  content_data:
  feed_data:
  profile_data:
  keycloak_postgres_db_data:
  rover_data:

networks:
  app-network:
    driver: bridge