
services:
  # Databases

  profile-db:
    image: postgres:15
    container_name: profile_db
    environment:
      POSTGRES_USER: ${PROFILE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROFILE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROFILE_POSTGRES_DB}
    ports:
      - "${PROFILE_DB_PORT}:${INNER_DB_PORT}"
    volumes:
      - profile_data:/var/lib/postgresql/data
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROFILE_POSTGRES_USER} -d ${PROFILE_POSTGRES_DB} -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25

  content-db:
    image: postgres:15
    container_name: content_db
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB}
    ports:
      - "${CONTENT_DB_PORT}:${INNER_DB_PORT}"
    volumes:
      - content_data:/var/lib/postgresql/data
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CONTENT_POSTGRES_USER} -d ${CONTENT_POSTGRES_DB} -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 25

  # DB migrators runners

  profile-db-migrator:
    build:
      context: ../database/profile-db
      dockerfile: Dockerfile.migrator
    container_name: profile_db_migrator
    depends_on:
      profile-db:
        condition: service_healthy
    networks:
      - reverie-network
    entrypoint: ["migrate", "-path=/app/migrations", "-database=postgres://${PROFILE_POSTGRES_USER}:${PROFILE_POSTGRES_PASSWORD}@profile-db:${INNER_DB_PORT}/${PROFILE_POSTGRES_DB}?sslmode=disable", "up"]

  content-db-migrator:
    build:
      context: ../database/content-db
      dockerfile: Dockerfile.migrator
    container_name: content_db_migrator
    depends_on:
      content-db:
        condition: service_healthy
    networks:
      - reverie-network
    entrypoint: ["migrate", "-path=/app/migrations", "-database=postgres://${CONTENT_POSTGRES_USER}:${CONTENT_POSTGRES_PASSWORD}@content-db:${INNER_DB_PORT}/${CONTENT_POSTGRES_DB}?sslmode=disable", "up"]

  # Backend

  profile-service:
    build:
      context: ../backend/profile-service
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: profile_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PROFILE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROFILE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROFILE_POSTGRES_DB}
      POSTGRES_HOST: profile-db
      PORT: ${INNER_SERVICE_PORT}
    depends_on:
      profile-db:
        condition: service_healthy
    ports:
      - "${PROFILE_PORT}:${INNER_SERVICE_PORT}"
    networks:
      - reverie-network
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 10
    #  start_period: 5s

  content-service:
    build:
      context: ../backend/content-service
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: content_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB}
      POSTGRES_HOST: content-db
      DB_PORT: ${CONTENT_DB_PORT}
      PORT: ${INNER_SERVICE_PORT}
    depends_on:
      content-db:
        condition: service_healthy
    ports:
      - "${CONTENT_PORT}:${INNER_SERVICE_PORT}"
    networks:
      - reverie-network
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 10
    #  start_period: 5s

  #feed-service:
  #  build:
  #    context: ../backend/feed-service
  #    dockerfile: Dockerfile
  #  container_name: feed_service
  #  restart: unless-stopped
  #  environment:
  #    PORT: ${INNER_SERVICE_PORT}
  #  ports:
  #    - "${FEED_PORT}:${INNER_SERVICE_PORT}"
  #  networks:
  #    - reverie-network
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 10
    #  start_period: 5s

  lamifare:
    build:
      context: ../backend/lamifare
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: lamifare
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_GROUP: ${KAFKA_GROUP}
      OPENSEARCH_URL: ${OPENSEARCH_HOSTS}
      PORT: ${INNER_SERVICE_PORT}
    ports:
      - "${LAMIFARE_PORT}:${INNER_SERVICE_PORT}"
    depends_on:
      kafka:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10

  # Infra

  # kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo stat | nc localhost ${ZOOKEEPER_CLIENT_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_INTERNAL_CLIENT_PORT},PLAINTEXT_HOST://localhost:${KAFKA_EXTERNAL_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
    ports:
      - "${KAFKA_EXTERNAL_CLIENT_PORT}:${KAFKA_EXTERNAL_CLIENT_PORT}"
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:${KAFKA_INTERNAL_CLIENT_PORT}", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_IMPORT_STRATEGY: IGNORE_EXISTING
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:${INNER_DB_PORT}/${KEYCLOAK_POSTGRES_DB}"
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:${INNER_SERVICE_PORT}"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    networks:
      - reverie-network

  keycloak-db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak_postgres_db_data:/var/lib/postgresql/data
    ports:
      - "${KEYCLOAK_DB_PORT}:${INNER_DB_PORT}"
    networks:
      - reverie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KEYCLOAK_POSTGRES_USER}", "-d", "${KEYCLOAK_POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # opensearch

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    #  - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_HTTP_PORT}:${OPENSEARCH_HTTP_PORT}"
      - "${OPENSEARCH_PA_PORT}:${OPENSEARCH_PA_PORT}"
    networks:
      - reverie-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${OPENSEARCH_HTTP_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["${OPENSEARCH_HOSTS}"]
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - "${OPENSEARCH_DASHBOARD_PORT}:${OPENSEARCH_DASHBOARD_PORT}"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - reverie-network

  # graphql stuff
  router:
    container_name: router
    image: ghcr.io/apollographql/apollo-runtime:latest
    ports:
      - "${ROUTER_PORT}:${ROUTER_INNER_PORT}"
    volumes:
      - rover_data:/config
    environment:
      APOLLO_KEY: ${APOLLO_KEY}
      APOLLO_GRAPH_REF: "${APOLLO_GRAPH_REF}"
      APOLLO_ROUTER_CONFIG_PATH: /config/router_config.yaml
      APOLLO_ROUTER_SUPERGRAPH_PATH: /config/schema.graphql
    networks:
      - reverie-network

volumes:
  profile_data:
  content_data:
  feed_data:
  keycloak_postgres_db_data:
  rover_data:
    external: true
  opensearch_data:
  zookeeper_data:
  kafka_data:

networks:
  reverie-network:
    driver: bridge
