version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data:/usr/share/nginx/html # Путь относительно docker-compose.yml
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
