query GetUserByNickTag($nickTag: String!) {
  userByTag(nickTag: $nickTag) {
    id
    nickname
    email
    nickTag
    profilePicture
    description
    status
    userRating
    followers {
      id
      nickname
    }
    following {
      id
      nickname
    }
  }
}

query GetUserById($userId: UUID!) {
  userById(userId: $userId) {
    id
    nickname
    email
    nickTag
    description
    userRating
    profilePicture
    followers {
        id
        nickname
    }
    following {
        id
        nickname
    }
      
  }
}

query GetPinsByUserId($userId: UUID!, $viewerId: UUID, $limit: Int = 10, $offset: Int = 0) {
  pinsByUser(userId: $userId, viewerId: $viewerId, limit: $limit, offset: $offset) {
    id
    name
    latitude
    longitude
    description
    rating
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

query GetLikedPinsByUserId($userID: UUID!, $limit: Int = 10, $offset: Int = 0) {
  likedPinsByUser(userID: $userID, limit: $limit, offset: $offset) {
    id
    name
    latitude
    longitude
    description
    rating
    createdAt
    owner {
      id
      nickname
      profilePicture
    }
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

query GetBookmarkedPinsByUserId($userID: UUID!, $limit: Int = 10, $offset: Int = 0) {
  bookmarkedPinsByUser(userID: $userID, limit: $limit, offset: $offset) {
    id
    name
    latitude
    longitude
    description
    rating
    createdAt
    owner {
      id
      nickname
      profilePicture
    }
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

mutation UpdatePin($id: UUID!, $input: UpdatePinInput!) {
  updatePin(id: $id, input: $input) {
    id
    name
    latitude
    longitude
    description
    rating
    createdAt
    owner {
      id
      nickname
      profilePicture
    }
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

mutation UpdateBoard($id: UUID!, $input: UpdateBoardInput!) {
  updateBoard(id: $id, input: $input) {
    id
    name
    description
    accessLevel
    ownerId
    authorId
    ownerType
    createdAt
    savedAt
    pins {
      id
      name
      owner {
        id
        nickname
        profilePicture
      }
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}


query GetOwnBoardsByUserId($userId: UUID!, $limit: Int = 10, $offset: Int = 0) {
  ownBoardsByUser(userId: $userId, limit: $limit, offset: $offset) {
    id
    name
    description
    accessLevel
    ownerId
    boardImageURL
    ownerType
    pins {
      id
      name
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}

query GetLikedBoardsByUserId($userID: UUID!, $limit: Int = 10, $offset: Int = 0) {
  likedBoardsByUser(userID: $userID, limit: $limit, offset: $offset) {
    id
    name
    description
    accessLevel
    ownerId
    authorId
    ownerType
    createdAt
    savedAt
    pins {
      id
      name
      owner {
        id
        nickname
        profilePicture
      }
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}

query GetBookmarkedBoardsByUserId($userID: UUID!, $limit: Int = 10, $offset: Int = 0) {
  bookmarkedBoardsByUser(userID: $userID, limit: $limit, offset: $offset) {
    id
    name
    description
    accessLevel
    ownerId
    authorId
    ownerType
    createdAt
    savedAt
    pins {
      id
      name
      owner {
        id
        nickname
        profilePicture
      }
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}

query GetUserIdByNickTag($nickTag: String!) {
  userByTag(nickTag: $nickTag) {
    id
  }
}

query GetFollowersById($userId: UUID!) {
  followersOf(userId: $userId)  {
    id
    nickname
    email
    nickTag
    profilePicture
    description
    status
    userRating
    followers {
      id
      nickname
    }
    following {
      id
      nickname
    }
  }
}

mutation CreateGroup($input: CreateGroupInput!){
  createGroup(input: $input) {
    id
    members {
      id
    }
  }
}

mutation CreateBoard($input: CreateBoardInput!){
  createBoard(input: $input) {
    id
    name
    description
    boardImageURL
    accessLevel
    ownerId
    ownerType
    pins {
      id
      name
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}

query GetPinById($id: UUID!) {
  pin(id: $id) {
    id
    name
    latitude
    longitude
    description
    rating
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

query GetBoardById($id: UUID!) {
  board(id: $id) {
    id
    name
    boardImageURL
    description
    accessLevel
    ownerId
    ownerType
    pins {
      id
      name
      images {
        id
        orderNumber
        imageUrl
      }
    }
    reactionId
    bookmarked
  }
}

mutation CreatePin($input: CreatePinInput!) {
  createPin(input: $input) {
    id
    name
    latitude
    longitude
    description
    rating
    createdAt
    images {
      id
      orderNumber
      imageUrl
    }
  }
}

mutation AddPinToBoard($pinId: UUID!, $boardId: UUID!) {
  addPinToBoard(pinId: $pinId, boardId: $boardId) {
    id
    name
    pins {
      id
      name
    }
  }
}

mutation RemovePinFromBoard($pinId: UUID!, $boardId: UUID!) {
  removePinFromBoard(pinId: $pinId, boardId: $boardId) {
    id
    name
    pins {
      id
      name
    }
  }
}

mutation updateCommentToPin($id: UUID!, $message: String!) {
  updateCommentToPin(id: UUID, message: $message) {
      message
  }
}

mutation updateCommentToBoard($id: UUID!, $message: String!) {
  updateCommentToBoard(id: UUID, message: $message) {
    message
  }
}

mutation deleteCommentToPin($id: UUID!) {
  deleteCommentToPin(id: $id)
}

mutation deleteCommentToBoard($id: UUID!) {
  deleteCommentToBoard(id: $id)
}

mutation AddImageToPin($input: AddImageInput!) {
  addImageToPin(input: $input) {
    id
    imageUrl
    orderNumber
  }
}

mutation RemoveImageFromPin($imageId: UUID!) {
  removeImageFromPin(imageId: $imageId)
}

mutation FollowUser($userId: UUID!, $followerId: UUID!) {
  followUser(userId: $userId, followerId: $followerId)
}

mutation UnfollowUser($userId: UUID!, $followerId: UUID!) {
  unfollowUser(userId: $userId, followerId: $followerId)
}

mutation UpdateUser($userId: UUID!, $input: UpdateUserInput!) {
  updateUser(userId: $userId, input: $input) {
    id
    nickname
    email
    nickTag
    profilePicture
    description
    status
    userRating
    followers {
      id
      nickname
    }
    following {
      id
      nickname
    }
  }
}

query GetCommentsByPinId($pinId: UUID!, $limit: Int = 10, $offset: Int = 0) {
  commentsByPin(pinId: $pinId, limit: $limit, offset: $offset) {
    id
    pinId
    message
    createdAt
    owner {
      id
      nickname
      profilePicture
    }
  }
}

mutation AddCommentToPin($input: AddCommentToPinInput!) {
  addCommentToPin(input: $input) {
    id
    pinId
    message
    createdAt
    owner {
      id
      nickname
    }
  }
}

mutation UpdatePinComment($id: UUID!, $message: String!) {
  updateCommentToPin(id: $id, message: $message) {
    id
    message
    createdAt
  }
}

mutation DeletePinComment($id: UUID!) {
  deleteCommentToPin(id: $id)
}

query GetCommentsByBoardId($boardId: UUID!, $limit: Int = 10, $offset: Int = 0) {
  commentsByBoard(boardId: $boardId, limit: $limit, offset: $offset) {
    id
    boardId
    message
    createdAt
    owner {
      id
      nickname
      profilePicture
    }
  }
}

mutation AddCommentToBoard($input: AddCommentToBoardInput!) {
  addCommentToBoard(input: $input) {
    id
    boardId
    message
    createdAt
    owner {
      id
      nickname
    }
  }
}

mutation UpdateBoardComment($id: UUID!, $message: String!) {
  updateCommentToBoard(id: $id, message: $message) {
    id
    message
    createdAt
  }
}

mutation DeleteBoardComment($id: UUID!) {
  deleteCommentToBoard(id: $id)
}

query GetAvailableReactions {
  reactions {
    id
    type
    description
  }
}

query CountAllReactionsToPin($pinId: UUID!) {
  countAllReactionsToPin(pinId: $pinId)
}

query CountAllReactionsToBoard($boardId: UUID!) {
  countAllReactionsToBoard(boardId: $boardId)
}

mutation ReactionToPin($pinId: UUID!, $reactionId: UUID!, $userId: UUID!) {
  reactionToPin(pinId: $pinId, reactionId: $reactionId, userId: $userId)
}

mutation ReactionToBoard($boardId: UUID!, $reactionId: UUID!, $userId: UUID!) {
  reactionToBoard(boardId: $boardId, reactionId: $reactionId, userId: $userId)
}

mutation BookmarkToPin($pinId: UUID!, $userId: UUID!) {
  bookmarkToPin(pinId: $pinId, userId: $userId)
}

mutation BookmarkToBoard($boardId: UUID!, $userId: UUID!) {
  bookmarkToBoard(boardId: $boardId, userId: $userId)
}

query GetPinReactionId($id: UUID!) {
  pin(id: $id) {
    reactionId
  }
}

query GetBoardReactionId($id: UUID!) {
  board(id: $id) {
    reactionId
  }
}

query IsPinBookmarked($id: UUID!) {
  pin(id: $id) {
    bookmarked
  }
}

query IsBoardBookmarked($id: UUID!) {
  board(id: $id) {
    bookmarked
  }
}