// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: geopb/geo.proto

package geopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_geopb_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{0}
}

func (x *GeocodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Address       *Address               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	mi := &file_geopb_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{1}
}

func (x *GeocodeResponse) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *GeocodeResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeocodeResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeocodeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GeocodeResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,4,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	Postcode      string                 `protobuf:"bytes,5,opt,name=postcode,proto3" json:"postcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_geopb_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *Address) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

type ReverseGeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeRequest) Reset() {
	*x = ReverseGeocodeRequest{}
	mi := &file_geopb_geo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeRequest) ProtoMessage() {}

func (x *ReverseGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeRequest.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseGeocodeRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ReverseGeocodeRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type ReverseGeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Address       *Address               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeResponse) Reset() {
	*x = ReverseGeocodeResponse{}
	mi := &file_geopb_geo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResponse) ProtoMessage() {}

func (x *ReverseGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResponse.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{4}
}

func (x *ReverseGeocodeResponse) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *ReverseGeocodeResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ReverseGeocodeResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ReverseGeocodeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ReverseGeocodeResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type BulkGeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGeocodeRequest) Reset() {
	*x = BulkGeocodeRequest{}
	mi := &file_geopb_geo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGeocodeRequest) ProtoMessage() {}

func (x *BulkGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGeocodeRequest.ProtoReflect.Descriptor instead.
func (*BulkGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{5}
}

func (x *BulkGeocodeRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type BulkGeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GeocodeResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGeocodeResponse) Reset() {
	*x = BulkGeocodeResponse{}
	mi := &file_geopb_geo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGeocodeResponse) ProtoMessage() {}

func (x *BulkGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geopb_geo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGeocodeResponse.ProtoReflect.Descriptor instead.
func (*BulkGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_geopb_geo_proto_rawDescGZIP(), []int{6}
}

func (x *BulkGeocodeResponse) GetResults() []*GeocodeResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_geopb_geo_proto protoreflect.FileDescriptor

const file_geopb_geo_proto_rawDesc = "" +
	"\n" +
	"\x0fgeopb/geo.proto\x12\x05geopb\"*\n" +
	"\x0eGeocodeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x9d\x01\n" +
	"\x0fGeocodeResponse\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12(\n" +
	"\aaddress\x18\x05 \x01(\v2\x0e.geopb.AddressR\aaddress\"\x8e\x01\n" +
	"\aAddress\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x04 \x01(\tR\vhouseNumber\x12\x1a\n" +
	"\bpostcode\x18\x05 \x01(\tR\bpostcode\";\n" +
	"\x15ReverseGeocodeRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\xa4\x01\n" +
	"\x16ReverseGeocodeResponse\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12(\n" +
	"\aaddress\x18\x05 \x01(\v2\x0e.geopb.AddressR\aaddress\"2\n" +
	"\x12BulkGeocodeRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"G\n" +
	"\x13BulkGeocodeResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.geopb.GeocodeResponseR\aresults2\xdb\x01\n" +
	"\n" +
	"GeoService\x128\n" +
	"\aGeocode\x12\x15.geopb.GeocodeRequest\x1a\x16.geopb.GeocodeResponse\x12M\n" +
	"\x0eReverseGeocode\x12\x1c.geopb.ReverseGeocodeRequest\x1a\x1d.geopb.ReverseGeocodeResponse\x12D\n" +
	"\vBulkGeocode\x12\x19.geopb.BulkGeocodeRequest\x1a\x1a.geopb.BulkGeocodeResponseB\bZ\x06/geopbb\x06proto3"

var (
	file_geopb_geo_proto_rawDescOnce sync.Once
	file_geopb_geo_proto_rawDescData []byte
)

func file_geopb_geo_proto_rawDescGZIP() []byte {
	file_geopb_geo_proto_rawDescOnce.Do(func() {
		file_geopb_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geopb_geo_proto_rawDesc), len(file_geopb_geo_proto_rawDesc)))
	})
	return file_geopb_geo_proto_rawDescData
}

var file_geopb_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_geopb_geo_proto_goTypes = []any{
	(*GeocodeRequest)(nil),         // 0: geopb.GeocodeRequest
	(*GeocodeResponse)(nil),        // 1: geopb.GeocodeResponse
	(*Address)(nil),                // 2: geopb.Address
	(*ReverseGeocodeRequest)(nil),  // 3: geopb.ReverseGeocodeRequest
	(*ReverseGeocodeResponse)(nil), // 4: geopb.ReverseGeocodeResponse
	(*BulkGeocodeRequest)(nil),     // 5: geopb.BulkGeocodeRequest
	(*BulkGeocodeResponse)(nil),    // 6: geopb.BulkGeocodeResponse
}
var file_geopb_geo_proto_depIdxs = []int32{
	2, // 0: geopb.GeocodeResponse.address:type_name -> geopb.Address
	2, // 1: geopb.ReverseGeocodeResponse.address:type_name -> geopb.Address
	1, // 2: geopb.BulkGeocodeResponse.results:type_name -> geopb.GeocodeResponse
	0, // 3: geopb.GeoService.Geocode:input_type -> geopb.GeocodeRequest
	3, // 4: geopb.GeoService.ReverseGeocode:input_type -> geopb.ReverseGeocodeRequest
	5, // 5: geopb.GeoService.BulkGeocode:input_type -> geopb.BulkGeocodeRequest
	1, // 6: geopb.GeoService.Geocode:output_type -> geopb.GeocodeResponse
	4, // 7: geopb.GeoService.ReverseGeocode:output_type -> geopb.ReverseGeocodeResponse
	6, // 8: geopb.GeoService.BulkGeocode:output_type -> geopb.BulkGeocodeResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geopb_geo_proto_init() }
func file_geopb_geo_proto_init() {
	if File_geopb_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geopb_geo_proto_rawDesc), len(file_geopb_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geopb_geo_proto_goTypes,
		DependencyIndexes: file_geopb_geo_proto_depIdxs,
		MessageInfos:      file_geopb_geo_proto_msgTypes,
	}.Build()
	File_geopb_geo_proto = out.File
	file_geopb_geo_proto_goTypes = nil
	file_geopb_geo_proto_depIdxs = nil
}
