{{- if .Values.apollo.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apollo-router-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APOLLO_KEY: {{ .Values.apollo.apiKey | quote }}
{{- end }}
