package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"context"

	"github.com/google/uuid"
)

// FindPinByID is the resolver for the findPinByID field.
func (r *entityResolver) FindPinByID(ctx context.Context, id uuid.UUID) (*model.Pin, error) {
	return r.Query().Pin(ctx, id, nil)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
