package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"content-service/internal/mapper"
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.Board, error) {
	board := mapper.CreateToDomainBoard(&input)
	board.ID = uuid.New()
	board.CreatedAt = time.Now()

	if err := r.BoardRepo.Create(ctx, *board); err != nil {
		return nil, err
	}
	return mapper.ToGraphQLBoard(board), nil
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, id uuid.UUID, input model.UpdateBoardInput) (*model.Board, error) {
	board := mapper.UpdateToDomainBoard(&input)

	err := r.BoardRepo.Update(ctx, id, *board)
	if err != nil {
		return nil, err
	}

	*board, err = r.BoardRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLBoard(board), nil
}

// CreatePin is the resolver for the createPin field.
func (r *mutationResolver) CreatePin(ctx context.Context, input model.CreatePinInput) (*model.Pin, error) {
	pin := mapper.CreateToDomainPin(&input)
	pin.ID = uuid.New()
	pin.CreatedAt = time.Now()

	if err := r.PinRepo.Create(ctx, *pin); err != nil {
		return nil, err
	}
	return mapper.ToGraphQLPin(pin), nil
}

// UpdatePin is the resolver for the updatePin field.
func (r *mutationResolver) UpdatePin(ctx context.Context, id uuid.UUID, input model.UpdatePinInput) (*model.Pin, error) {
	pin := mapper.UpdateToDomainPin(&input)

	prevPin, err := r.PinRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if prevPin.OwnerID != input.UserID {
		return nil, errors.New("incorrect user (not pin`s owner)")
	}

	err = r.PinRepo.Update(ctx, id, *pin)
	if err != nil {
		return nil, err
	}

	*pin, err = r.PinRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLPin(pin), nil
}

// AddPinToBoard is the resolver for the addPinToBoard field.
func (r *mutationResolver) AddPinToBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	board, err := r.BoardRepo.AddPinToBoard(ctx, pinID, boardID)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLBoard(board), nil
}

// RemovePinFromBoard is the resolver for the removePinFromBoard field.
func (r *mutationResolver) RemovePinFromBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	board, err := r.BoardRepo.RemovePinFromBoard(ctx, pinID, boardID)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLBoard(board), nil
}

// AddCommentToPin is the resolver for the addCommentToPin field.
func (r *mutationResolver) AddCommentToPin(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	comment, err := r.PinRepo.AddComment(ctx, input.PinID, input.UserID, input.Content)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id uuid.UUID, content string) (*model.Comment, error) {
	comment, err := r.PinRepo.UpdateComment(ctx, id, content)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.PinRepo.DeleteCommentByID(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddImageToPin is the resolver for the addImageToPin field.
func (r *mutationResolver) AddImageToPin(ctx context.Context, input model.AddImageInput) (*model.PinImage, error) {
	pinImage, err := r.PinRepo.AddPinImage(ctx, input.PinID, input.ImageURL, input.OrderNumber)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLPinImage(pinImage), nil
}

// RemoveImageFromPin is the resolver for the removeImageFromPin field.
func (r *mutationResolver) RemoveImageFromPin(ctx context.Context, imageID uuid.UUID) (bool, error) {
	err := r.PinRepo.DeletePinImage(ctx, imageID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// UpdateImageOrder is the resolver for the updateImageOrder field.
func (r *mutationResolver) UpdateImageOrder(ctx context.Context, imageID uuid.UUID, newOrder int) (*model.PinImage, error) {
	pinImage, err := r.PinRepo.UpdatePinImageOrder(ctx, imageID, newOrder)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLPinImage(pinImage), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
