package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: CreateBoard - createBoard"))
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, id uuid.UUID, input model.UpdateBoardInput) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: UpdateBoard - updateBoard"))
}

// CreatePin is the resolver for the createPin field.
func (r *mutationResolver) CreatePin(ctx context.Context, input model.CreatePinInput) (*model.Pin, error) {
	panic(fmt.Errorf("not implemented: CreatePin - createPin"))
}

// UpdatePin is the resolver for the updatePin field.
func (r *mutationResolver) UpdatePin(ctx context.Context, id uuid.UUID, input model.UpdatePinInput) (*model.Pin, error) {
	panic(fmt.Errorf("not implemented: UpdatePin - updatePin"))
}

// AddPinToBoard is the resolver for the addPinToBoard field.
func (r *mutationResolver) AddPinToBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: AddPinToBoard - addPinToBoard"))
}

// RemovePinFromBoard is the resolver for the removePinFromBoard field.
func (r *mutationResolver) RemovePinFromBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: RemovePinFromBoard - removePinFromBoard"))
}

// AddCommentToPin is the resolver for the addCommentToPin field.
func (r *mutationResolver) AddCommentToPin(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: AddCommentToPin - addCommentToPin"))
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id uuid.UUID, content string) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: UpdateComment - updateComment"))
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteComment - deleteComment"))
}

// AddImageToPin is the resolver for the addImageToPin field.
func (r *mutationResolver) AddImageToPin(ctx context.Context, input model.AddImageInput) (*model.PinImage, error) {
	panic(fmt.Errorf("not implemented: AddImageToPin - addImageToPin"))
}

// RemoveImageFromPin is the resolver for the removeImageFromPin field.
func (r *mutationResolver) RemoveImageFromPin(ctx context.Context, imageID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveImageFromPin - removeImageFromPin"))
}

// UpdateImageOrder is the resolver for the updateImageOrder field.
func (r *mutationResolver) UpdateImageOrder(ctx context.Context, imageID uuid.UUID, newOrder int) (*model.PinImage, error) {
	panic(fmt.Errorf("not implemented: UpdateImageOrder - updateImageOrder"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
