package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"content-service/internal/mapper"
	"content-service/internal/models"
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "CreateBoard"))
	logger.Info("Creating board")

	board := mapper.CreateToDomainBoard(&input)
	board.ID = uuid.New()
	board.CreatedAt = time.Now()

	if err := r.BoardRepo.Create(ctx, *board); err != nil {
		logger.Error("Failed to create board", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully created board", zap.String("boardID", board.ID.String()))
	return mapper.ToGraphQLBoard(board), nil
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, id uuid.UUID, input model.UpdateBoardInput) (*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "UpdateBoard"), zap.String("boardID", id.String()))
	logger.Info("Updating board")

	board := mapper.UpdateToDomainBoard(&input)

	err := r.BoardRepo.Update(ctx, id, *board)
	if err != nil {
		logger.Error("Failed to update board", zap.Error(err))
		return nil, err
	}

	*board, err = r.BoardRepo.GetByID(ctx, id)
	if err != nil {
		logger.Error("Failed to fetch updated board", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully updated board")
	return mapper.ToGraphQLBoard(board), nil
}

// CreatePin is the resolver for the createPin field.
func (r *mutationResolver) CreatePin(ctx context.Context, input model.CreatePinInput) (*model.Pin, error) {
	logger := zap.L().With(zap.String("resolver", "CreatePin"))
	logger.Info("Creating pin")

	pin := mapper.CreateToDomainPin(&input)
	pin.ID = uuid.New()
	pin.CreatedAt = time.Now()

	if err := r.PinRepo.Create(ctx, *pin); err != nil {
		logger.Error("Failed to create pin", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully created pin", zap.String("pinID", pin.ID.String()))
	return mapper.ToGraphQLPin(pin), nil
}

// UpdatePin is the resolver for the updatePin field.
func (r *mutationResolver) UpdatePin(ctx context.Context, id uuid.UUID, input model.UpdatePinInput) (*model.Pin, error) {
	logger := zap.L().With(zap.String("resolver", "UpdatePin"), zap.String("pinID", id.String()))
	logger.Info("Updating pin")

	pin := mapper.UpdateToDomainPin(&input)

	prevPin, err := r.PinRepo.GetByID(ctx, id)
	if err != nil {
		logger.Error("Failed to fetch existing pin", zap.Error(err))
		return nil, err
	}
	if prevPin.OwnerID != input.UserID {
		logger.Warn("User is not owner of pin", zap.String("userID", input.UserID.String()))
		return nil, errors.New("incorrect user (not pin`s owner)")
	}

	err = r.PinRepo.Update(ctx, id, *pin)
	if err != nil {
		logger.Error("Failed to update pin", zap.Error(err))
		return nil, err
	}

	*pin, err = r.PinRepo.GetByID(ctx, id)
	if err != nil {
		logger.Error("Failed to fetch updated pin", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully updated pin")
	return mapper.ToGraphQLPin(pin), nil
}

// AddPinToBoard is the resolver for the addPinToBoard field.
func (r *mutationResolver) AddPinToBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "AddPinToBoard"), zap.String("pinID", pinID.String()), zap.String("boardID", boardID.String()))
	logger.Info("Adding pin to board")

	board, err := r.BoardRepo.AddPinToBoard(ctx, pinID, boardID)
	if err != nil {
		logger.Error("Failed to add pin to board", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully added pin to board")
	return mapper.ToGraphQLBoard(board), nil
}

// RemovePinFromBoard is the resolver for the removePinFromBoard field.
func (r *mutationResolver) RemovePinFromBoard(ctx context.Context, pinID uuid.UUID, boardID uuid.UUID) (*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "RemovePinFromBoard"), zap.String("pinID", pinID.String()), zap.String("boardID", boardID.String()))
	logger.Info("Removing pin from board")

	board, err := r.BoardRepo.RemovePinFromBoard(ctx, pinID, boardID)
	if err != nil {
		logger.Error("Failed to remove pin from board", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully removed pin from board")
	return mapper.ToGraphQLBoard(board), nil
}

// AddCommentToPin is the resolver for the addCommentToPin field.
func (r *mutationResolver) AddCommentToPin(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	logger := zap.L().With(zap.String("resolver", "AddCommentToPin"), zap.String("pinID", input.PinID.String()))
	logger.Info("Adding comment to pin")

	comment, err := r.PinRepo.AddComment(ctx, input.PinID, input.UserID, input.Content)
	if err != nil {
		logger.Error("Failed to add comment", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully added comment")
	return mapper.ToGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id uuid.UUID, content string) (*model.Comment, error) {
	logger := zap.L().With(zap.String("resolver", "UpdateComment"), zap.String("commentID", id.String()))
	logger.Info("Updating comment")

	comment, err := r.PinRepo.UpdateComment(ctx, id, content)
	if err != nil {
		logger.Error("Failed to update comment", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully updated comment")
	return mapper.ToGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id uuid.UUID) (bool, error) {
	logger := zap.L().With(zap.String("resolver", "DeleteComment"), zap.String("commentID", id.String()))
	logger.Info("Deleting comment")

	err := r.PinRepo.DeleteCommentByID(ctx, id)
	if err != nil {
		logger.Error("Failed to delete comment", zap.Error(err))
		return false, err
	}

	logger.Info("Successfully deleted comment")
	return true, nil
}

// AddImageToPin is the resolver for the addImageToPin field.
func (r *mutationResolver) AddImageToPin(ctx context.Context, input model.AddImageInput) (*model.PinImage, error) {
	logger := zap.L().With(zap.String("resolver", "AddImageToPin"), zap.String("pinID", input.PinID.String()))
	logger.Info("Adding image to pin")

	pinImage, err := r.PinRepo.AddPinImage(ctx, input.PinID, input.ImageURL, input.OrderNumber)
	if err != nil {
		logger.Error("Failed to add image to pin", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully added image to pin")
	return mapper.ToGraphQLPinImage(pinImage), nil
}

// RemoveImageFromPin is the resolver for the removeImageFromPin field.
func (r *mutationResolver) RemoveImageFromPin(ctx context.Context, imageID uuid.UUID) (bool, error) {
	logger := zap.L().With(zap.String("resolver", "RemoveImageFromPin"), zap.String("imageID", imageID.String()))
	logger.Info("Removing image from pin")

	err := r.PinRepo.DeletePinImage(ctx, imageID)
	if err != nil {
		logger.Error("Failed to remove image", zap.Error(err))
		return false, err
	}

	logger.Info("Successfully removed image from pin")
	return true, nil
}

// UpdateImageOrder is the resolver for the updateImageOrder field.
func (r *mutationResolver) UpdateImageOrder(ctx context.Context, imageID uuid.UUID, newOrder int) (*model.PinImage, error) {
	logger := zap.L().With(zap.String("resolver", "UpdateImageOrder"), zap.String("imageID", imageID.String()))
	logger.Info("Updating image order")

	pinImage, err := r.PinRepo.UpdatePinImageOrder(ctx, imageID, newOrder)
	if err != nil {
		logger.Error("Failed to update image order", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully updated image order")
	return mapper.ToGraphQLPinImage(pinImage), nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	group := &models.Group{}

	if err := r.BoardRepo.CreateGroup(ctx, *group); err != nil {
		return nil, fmt.Errorf("failed to create group: %w", err)
	}

	var members []models.Member
	for _, userID := range input.Members {

		member := models.Member{
			UserID:  userID,
			GroupID: group.ID,
		}

		if err := r.BoardRepo.CreateMember(ctx, member); err != nil {
			return nil, fmt.Errorf("failed to add user %s to group: %w", userID, err)
		}

		members = append(members, member)
	}

	return mapper.ToGraphQLGroup(group, members), nil
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (bool, error) {
	if _, err := r.BoardRepo.GetMember(ctx, userID, groupID); err == nil {
		return false, fmt.Errorf("user already in the group")
	}

	member := &models.Member{
		UserID:  userID,
		GroupID: groupID,
	}

	if err := r.BoardRepo.CreateMember(ctx, *member); err != nil {
		return false, fmt.Errorf("failed to add user to group: %w", err)
	}

	return true, nil
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (bool, error) {
	member, err := r.BoardRepo.GetMember(ctx, userID, groupID)
	if err != nil {
		return false, fmt.Errorf("user %s not in group %s", userID, groupID)
	}

	if err := r.BoardRepo.RemoveUserFromGroup(ctx, member); err != nil {
		return false, fmt.Errorf("failed to remove user from group: %w", err)
	}

	return true, nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, groupID uuid.UUID) (bool, error) {
	// Жесткого удаления скорее всего не будет, пока нет требований останется заглушкой
	return false, nil

	// var group models.Group
	// if err := r.DB.First(&group, "id = ?", id).Error; err != nil {
	// 	return false, fmt.Errorf("group not found: %w", err)
	// }

	// if err := r.DB.Delete(&group).Error; err != nil {
	// 	return false, fmt.Errorf("failed to delete group: %w", err)
	// }

	// return true, nil
}

// RequestJoinGroup is the resolver for the requestJoinGroup field.
func (r *mutationResolver) RequestJoinGroup(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestJoinGroup - requestJoinGroup"))
}

// AcceptJoinToGroup is the resolver for the acceptJoinToGroup field.
func (r *mutationResolver) AcceptJoinToGroup(ctx context.Context, requestID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: AcceptJoinToGroup - acceptJoinToGroup"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
