package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"content-service/internal/mapper"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id uuid.UUID) (*model.Board, error) {
	board, err := r.BoardRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLBoard(&board), nil
}

// BoardByName is the resolver for the boardByName field.
func (r *queryResolver) BoardByName(ctx context.Context, name string) ([]*model.Board, error) {
	boards, err := r.BoardRepo.GetByName(ctx, name)
	if err != nil {
		return nil, err
	}
	var retBoards []*model.Board
	for i := range boards {
		retBoards = append(retBoards, mapper.ToGraphQLBoard(&boards[i]))
	}
	return retBoards, nil
}

// BoardsByGroup is the resolver for the boardsByGroup field.
func (r *queryResolver) BoardsByGroup(ctx context.Context, groupID uuid.UUID) ([]*model.Board, error) {
	boards, err := r.BoardRepo.GetByGroup(ctx, groupID)
	if err != nil {
		return nil, err
	}
	var retBoards []*model.Board
	for i := range boards {
		retBoards = append(retBoards, mapper.ToGraphQLBoard(&boards[i]))
	}
	return retBoards, nil
}

// Pin is the resolver for the pin field.
func (r *queryResolver) Pin(ctx context.Context, id uuid.UUID) (*model.Pin, error) {
	pin, err := r.PinRepo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLPin(&pin), nil
}

// PinsByUser is the resolver for the pinsByUser field.
func (r *queryResolver) PinsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Pin, error) {
	pins, err := r.PinRepo.GetByUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	var retPins []*model.Pin
	for i := range pins {
		retPins = append(retPins, mapper.ToGraphQLPin(&pins[i]))
	}
	return retPins, nil
}

// PinsByName is the resolver for the pinsByName field.
func (r *queryResolver) PinsByName(ctx context.Context, name string) ([]*model.Pin, error) {
	pins, err := r.PinRepo.GetByName(ctx, name)
	if err != nil {
		return nil, err
	}
	var retPins []*model.Pin
	for i := range pins {
		retPins = append(retPins, mapper.ToGraphQLPin(&pins[i]))
	}
	return retPins, nil
}

// PinsByLocation is the resolver for the pinsByLocation field.
func (r *queryResolver) PinsByLocation(ctx context.Context, query string) ([]*model.Pin, error) {
	panic(fmt.Errorf("not implemented: PinsByLocation - pinsByLocation"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
