package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"content-service/internal/mapper"
	"content-service/internal/models"
	"context"
	"fmt"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id uuid.UUID) (*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "Board"), zap.String("boardID", id.String()))
	logger.Info("Fetching board")

	board, err := r.BoardRepo.GetByID(ctx, id)
	if err != nil {
		logger.Error("Failed to fetch board", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully fetched board")
	return mapper.ToGraphQLBoard(&board), nil
}

// BoardByName is the resolver for the boardByName field.
func (r *queryResolver) BoardByName(ctx context.Context, name string) ([]*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "BoardByName"), zap.String("name", name))
	logger.Info("Fetching boards by name")

	boards, err := r.BoardRepo.GetByName(ctx, name)
	if err != nil {
		logger.Error("Failed to fetch boards", zap.Error(err))
		return nil, err
	}

	var retBoards []*model.Board
	for i := range boards {
		retBoards = append(retBoards, mapper.ToGraphQLBoard(&boards[i]))
	}

	logger.Info("Successfully fetched boards", zap.Int("count", len(retBoards)))
	return retBoards, nil
}

// BoardsByGroup is the resolver for the boardsByGroup field.
func (r *queryResolver) BoardsByGroup(ctx context.Context, groupID uuid.UUID) ([]*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "BoardsByGroup"), zap.String("groupID", groupID.String()))
	logger.Info("Fetching boards by group")

	boards, err := r.BoardRepo.GetByGroup(ctx, groupID)
	if err != nil {
		logger.Error("Failed to fetch boards", zap.Error(err))
		return nil, err
	}

	var retBoards []*model.Board
	for i := range boards {
		retBoards = append(retBoards, mapper.ToGraphQLBoard(&boards[i]))
	}

	logger.Info("Successfully fetched boards", zap.Int("count", len(retBoards)))
	return retBoards, nil
}

// Pin is the resolver for the pin field.
func (r *queryResolver) Pin(ctx context.Context, id uuid.UUID) (*model.Pin, error) {
	logger := zap.L().With(zap.String("resolver", "Pin"), zap.String("pinID", id.String()))
	logger.Info("Fetching pin")

	pin, err := r.PinRepo.GetByID(ctx, id)
	if err != nil {
		logger.Error("Failed to fetch pin", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully fetched pin")
	return mapper.ToGraphQLPin(&pin), nil
}

// PinsByUser is the resolver for the pinsByUser field.
func (r *queryResolver) PinsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Pin, error) {
	logger := zap.L().With(zap.String("resolver", "PinsByUser"), zap.String("userID", userID.String()))
	logger.Info("Fetching pins by user")

	pins, err := r.PinRepo.GetByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to fetch pins", zap.Error(err))
		return nil, err
	}

	var retPins []*model.Pin
	for i := range pins {
		retPins = append(retPins, mapper.ToGraphQLPin(&pins[i]))
	}

	logger.Info("Successfully fetched pins", zap.Int("count", len(retPins)))
	return retPins, nil
}

// PinsByName is the resolver for the pinsByName field.
func (r *queryResolver) PinsByName(ctx context.Context, name string) ([]*model.Pin, error) {
	logger := zap.L().With(zap.String("resolver", "PinsByName"), zap.String("name", name))
	logger.Info("Fetching pins by name")

	pins, err := r.PinRepo.GetByName(ctx, name)
	if err != nil {
		logger.Error("Failed to fetch pins", zap.Error(err))
		return nil, err
	}

	var retPins []*model.Pin
	for i := range pins {
		retPins = append(retPins, mapper.ToGraphQLPin(&pins[i]))
	}

	logger.Info("Successfully fetched pins", zap.Int("count", len(retPins)))
	return retPins, nil
}

// PinsByLocation is the resolver for the pinsByLocation field.
func (r *queryResolver) PinsByLocation(ctx context.Context, query string) ([]*model.Pin, error) {
	panic(fmt.Errorf("not implemented: PinsByLocation - pinsByLocation"))
}

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, groupID uuid.UUID) (*model.Group, error) {
	logger := zap.L().With(zap.String("resolver", "GroupByID"), zap.String("groupID", groupID.String()))
	logger.Info("Fetching group")

	group, err := r.BoardRepo.GetGroupByID(ctx, groupID)
	if err != nil {
		logger.Error("Failed to fetch group", zap.Error(err))
		return nil, err
	}

	logger.Info("Successfully fetched group")
	return mapper.ToGraphQLGroup(&group), nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (bool, error) {
	logger := zap.L().With(zap.String("resolver", "IsUserInGroup"), zap.String("groupID", groupID.String()), zap.String("userID", userID.String()))
	logger.Info("Checking if the user is in the group")

	isMember, err := r.BoardRepo.GetMember(ctx, userID, groupID)
	if err != nil {
		logger.Error("Failed to check if the user is in the group", zap.Error(err))
		return false, err
	}

	return isMember, nil
}

// GroupsOfUser is the resolver for the groupsOfUser field.
func (r *queryResolver) GroupsOfUser(ctx context.Context, userID uuid.UUID) ([]*model.Group, error) {
	logger := zap.L().With(zap.String("resolver", "GroupsOfUser"), zap.String("userID", userID.String()))
	logger.Info("Fetching groups of user")

	var members []models.Member
	members, err := r.BoardRepo.GetGroups(ctx, userID)
	if err != nil {
		logger.Error("Failed to find groups for user", zap.Error(err))
		return nil, err
	}

	var groups []*model.Group
	for _, member := range members {
		var group models.Group
		if group, err = r.BoardRepo.GetGroupByID(ctx, member.GroupID); err != nil {
			logger.Error("Failed to get composition of groups with user", zap.Error(err))
			return nil, err
		}

		groups = append(groups, mapper.ToGraphQLGroup(&group))
	}

	return groups, nil
}

// CommentsByBoard is the resolver for the commentsByBoard field.
func (r *queryResolver) CommentsByBoard(ctx context.Context, boardID uuid.UUID) ([]*model.CommentToBoard, error) {
	logger := zap.L().With(zap.String("resolver", "CommentsByBoard"), zap.String("boardID", boardID.String()))
	logger.Info("Fetching comments by board")

	comments_row, err := r.BoardRepo.GetCommentsByBoard(ctx, boardID)
	if err != nil {
		logger.Error("Failed to fetch comments by board", zap.Error(err))
		return nil, err
	}

	var comments []*model.CommentToBoard
	for _, comment := range comments_row {
		comments = append(comments, mapper.ToGraphQLCommentToBoard(&comment))
	}

	logger.Info("Successfully fetched comments by board")
	return comments, nil
}

// CommentsByPin is the resolver for the commentsByPin field.
func (r *queryResolver) CommentsByPin(ctx context.Context, pinID uuid.UUID) ([]*model.CommentToPin, error) {
	logger := zap.L().With(zap.String("resolver", "CommentsByPin"), zap.String("pinID", pinID.String()))
	logger.Info("Fetching comments by pin")

	comments_row, err := r.PinRepo.GetCommentsByPin(ctx, pinID)
	if err != nil {
		logger.Error("Failed to fetch comments by pin", zap.Error(err))
		return nil, err
	}

	var comments []*model.CommentToPin
	for _, comment := range comments_row {
		comments = append(comments, mapper.ToGraphQLCommentToPin(&comment))
	}

	logger.Info("Successfully fetched comments by pin")
	return comments, nil
}

// OwnBoardsByUser is the resolver for the ownBoardsByUser field.
func (r *queryResolver) OwnBoardsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "OwnBoardsByUser"), zap.String("userID", userID.String()))
	logger.Info("Fetching own boards by user")

	var boards []models.Board
	boards, err := r.BoardRepo.GetOwnBoardsByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to fetch own boards by user", zap.Error(err))
		return nil, err
	}

	retBoards := make([]*model.Board, len(boards))
	for i := range boards {
		retBoards[i] = mapper.ToGraphQLBoard(&boards[i])
	}

	logger.Info("Successfully fetched own boards by user", zap.Int("count", len(retBoards)))
	return retBoards, nil
}

// GroupBoardsByUser is the resolver for the groupBoardsByUser field.
func (r *queryResolver) GroupBoardsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Board, error) {
	logger := zap.L().With(zap.String("resolver", "GroupBoardsByUser"), zap.String("userID", userID.String()))
	logger.Info("Fetching group boards by user")

	var boards []models.Board
	boards, err := r.BoardRepo.GetGroupBoardsByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to fetch group boards by user", zap.Error(err))
		return nil, err
	}

	retBoards := make([]*model.Board, len(boards))
	for i := range boards {
		retBoards[i] = mapper.ToGraphQLBoard(&boards[i])
	}

	logger.Info("Successfully fetched group boards by user", zap.Int("count", len(retBoards)))
	return retBoards, nil
}

// CountOwnBoardsByUser is the resolver for the countOwnBoardsByUser field.
func (r *queryResolver) CountOwnBoardsByUser(ctx context.Context, userID uuid.UUID) (int, error) {
	logger := zap.L().With(zap.String("resolver", "CountOwnBoardsByUser"), zap.String("userID", userID.String()))
	logger.Info("Counting own boards by user")

	boardsNumber, err := r.BoardRepo.CountBoardsByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to count own boards by user", zap.Error(err))
		return 0, err
	}

	return int(boardsNumber), nil
}

// CountGroupBoardsByUser is the resolver for the countGroupBoardsByUser field.
func (r *queryResolver) CountGroupBoardsByUser(ctx context.Context, userID uuid.UUID) (int, error) {
	logger := zap.L().With(zap.String("resolver", "CountGroupBoardsByUser"), zap.String("userID", userID.String()))
	logger.Info("Counting group boards by user")

	boardsNumber, err := r.BoardRepo.CountGroupBoardsByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to count group boards by user", zap.Error(err))
		return 0, err
	}

	return int(boardsNumber), nil
}

// CountPinsByUser is the resolver for the countPinsByUser field.
func (r *queryResolver) CountPinsByUser(ctx context.Context, userID uuid.UUID) (int, error) {
	logger := zap.L().With(zap.String("resolver", "CountPinsByUser"), zap.String("userID", userID.String()))
	logger.Info("Counting own pins by user")

	pinsNumber, err := r.PinRepo.CountPinsByUser(ctx, userID)
	if err != nil {
		logger.Error("Failed to count own pins by user", zap.Error(err))
		return 0, err
	}

	return int(pinsNumber), nil
}

// Reactions is the resolver for the reactions field.
func (r *queryResolver) Reactions(ctx context.Context) ([]*model.Reaction, error) {
	logger := zap.L().With(zap.String("resolver", "Reactions"))
	logger.Info("Fetching reactions")

	reactions, err := r.ReactionRepo.GetAll(ctx)
	if err != nil {
		logger.Error("Failed to fetch reactions", zap.Error(err))
		return nil, err
	}
	var retReactions []*model.Reaction
	for i := range reactions {
		retReactions = append(retReactions, mapper.ToGraphQLReaction(&reactions[i]))
	}
	return retReactions, nil
}

// CountAllReactionsToPin is the resolver for the countAllReactionsToPin field.
func (r *queryResolver) CountAllReactionsToPin(ctx context.Context, pinID uuid.UUID) (int, error) {
	logger := zap.L().With(zap.String("resolver", "CountAllReactionsToPin"), zap.String("pinID", pinID.String()))
	logger.Info("Counting all reactions to pin")

	res, err := r.ReactionRepo.CountTotalReactionsInPin(ctx, pinID)
	if err != nil {
		logger.Error("Failed to count all reactions to pin", zap.Error(err))
		return 0, err
	}

	return int(res), err // ask no questions about my int conversion :)
}

// CountAllReactionsToBoard is the resolver for the countAllReactionsToBoard field.
func (r *queryResolver) CountAllReactionsToBoard(ctx context.Context, boardID uuid.UUID) (int, error) {
	logger := zap.L().With(zap.String("resolver", "CountAllReactionsToBoard"), zap.String("boardID", boardID.String()))
	logger.Info("Counting all reactions to board")

	res, err := r.ReactionRepo.CountTotalReactionsInBoard(ctx, boardID)
	if err != nil {
		logger.Error("Failed to count all reactions to board", zap.Error(err))
		return 0, err
	}

	return int(res), err // ask no questions about my int conversion :)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
