package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"content-service/graph/generated"
	"content-service/graph/model"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id uuid.UUID) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: Board - board"))
}

// BoardByName is the resolver for the boardByName field.
func (r *queryResolver) BoardByName(ctx context.Context, name string) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: BoardByName - boardByName"))
}

// BoardsByUser is the resolver for the boardsByUser field.
func (r *queryResolver) BoardsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Board, error) {
	panic(fmt.Errorf("not implemented: BoardsByUser - boardsByUser"))
}

// Pin is the resolver for the pin field.
func (r *queryResolver) Pin(ctx context.Context, id uuid.UUID) (*model.Pin, error) {
	panic(fmt.Errorf("not implemented: Pin - pin"))
}

// PinsByUser is the resolver for the pinsByUser field.
func (r *queryResolver) PinsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Pin, error) {
	panic(fmt.Errorf("not implemented: PinsByUser - pinsByUser"))
}

// PinsByName is the resolver for the pinsByName field.
func (r *queryResolver) PinsByName(ctx context.Context, name string) ([]*model.Pin, error) {
	panic(fmt.Errorf("not implemented: PinsByName - pinsByName"))
}

// PinsByLocation is the resolver for the pinsByLocation field.
func (r *queryResolver) PinsByLocation(ctx context.Context, query string) ([]*model.Pin, error) {
	panic(fmt.Errorf("not implemented: PinsByLocation - pinsByLocation"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
