server:
  port:
    8000

logging:
  level:
    root: INFO
    d.zhdanov.geoapi.fetchers.GeoFetcher: DEBUG
    d.zhdanov.geoapi.service.YandexGeoService: DEBUG
spring:
  application:
    name: geo-api

env:
  geoApiUrl: ${GEO_API_URL}
  geoApiKey: ${GEO_API_KEY}
