// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateGroupInput struct {
	MemberIds []string `json:"memberIds"`
}

type CreateUserInput struct {
	Nickname       string  `json:"nickname"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Description    *string `json:"description,omitempty"`
}

type Group struct {
	ID      string  `json:"id"`
	Members []*User `json:"members"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Nickname       *string `json:"nickname,omitempty"`
	Email          *string `json:"email,omitempty"`
	Password       *string `json:"password,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Description    *string `json:"description,omitempty"`
}

type User struct {
	ID             string  `json:"id"`
	Nickname       string  `json:"nickname"`
	Email          string  `json:"email"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Description    *string `json:"description,omitempty"`
	UserRating     float64 `json:"userRating"`
	Followers      []*User `json:"followers"`
	Following      []*User `json:"following"`
}
