supergraph:
  listen: 0.0.0.0:4000
  path: /
  introspection: true

sandbox:
  enabled: true

homepage:
  enabled: false

rhai:
  scripts: "/config/rhai"

headers:
  all:
    request:
      - propagate:
          matching: "x-user-id"

health_check:
  listen: 0.0.0.0:8088
  enabled: true
  path: /health

telemetry:
  exporters:
    logging:
      common:
        service_name: "apollo-router"

cors:
  allow_any_origin: true
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allow_headers: []
  expose_headers: []

authentication:
  router:
    jwt:
      jwks: 
        - url: "http://keycloak:8080/realms/reverie-realm/protocol/openid-connect/certs"
      header_name: Authorization
      header_value_prefix: Bearer
      on_error: Continue
      sources:
        - type: header
          name: Authorization
          value_prefix: Bearer
        - type: header
          name: X-Authorization
          value_prefix: Bearer
        - type: cookie
          name: authz

authorization:
  require_authentication: false