package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"github.com/google/uuid"
	"profile-service/internal/db/models"
	"profile-service/internal/graph/generated"
	"profile-service/internal/graph/mapping"
	"profile-service/internal/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	panic(fmt.Errorf("not implemented: FollowUser - followUser"))
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnfollowUser - unfollowUser"))
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	panic(fmt.Errorf("not implemented: CreateGroup - createGroup"))
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	panic(fmt.Errorf("not implemented: AddUserToGroup - addUserToGroup"))
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveUserFromGroup - removeUserFromGroup"))
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGroup - deleteGroup"))
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	userId, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid UUID format: %w", err)
	}

	var user models.User
	if err := r.DB.First(&user, userId).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return mapping.MapUserToGraphQL(&user), err
}

// UserByNickname is the resolver for the userByNickname field.
func (r *queryResolver) UserByNickname(ctx context.Context, nickname string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserByNickname - userByNickname"))
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserByEmail - userByEmail"))
}

// FollowersOf is the resolver for the followersOf field.
func (r *queryResolver) FollowersOf(ctx context.Context, userID string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: FollowersOf - followersOf"))
}

// FollowingOf is the resolver for the followingOf field.
func (r *queryResolver) FollowingOf(ctx context.Context, userID string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: FollowingOf - followingOf"))
}

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, id string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GroupByID - groupById"))
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	panic(fmt.Errorf("not implemented: IsUserInGroup - isUserInGroup"))
}

// GroupsOfUser is the resolver for the groupsOfUser field.
func (r *queryResolver) GroupsOfUser(ctx context.Context, userID string) ([]*model.Group, error) {
	panic(fmt.Errorf("not implemented: GroupsOfUser - groupsOfUser"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

//TODO
/*func (r *Resolver) User() generated.UserResolver {
	return &userResolver{r}
}*/

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
