package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"github.com/google/uuid"
	"profile-service/internal/db/models"
	"profile-service/internal/graph/generated"
	"profile-service/internal/graph/mapping"
	"profile-service/internal/graph/model"
	"profile-service/pkg/middleware"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	userId, err := middleware.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unautorized: %w", err)
	}

	var existing models.User
	if err := r.DB.First(&existing, "id = ?", userId).Error; err == nil {
		return nil, fmt.Errorf("user already exists")
	}

	user := &models.User{
		ID:             uuid.MustParse(userId),
		Nickname:       input.Nickname,
		Email:          input.Email,
		ProfilePicture: input.ProfilePicture,
		Description:    input.Description,
		UserRating:     0,
	}

	if err := r.DB.Create(user).Error; err != nil {
		return nil, err
	}

	return mapping.MapUserToGraphQL(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	if input.Nickname != nil {
		user.Nickname = *input.Nickname
	}
	if input.Email != nil {
		user.Email = *input.Email
	}
	if input.ProfilePicture != nil {
		user.ProfilePicture = input.ProfilePicture
	}
	if input.Description != nil {
		user.Description = input.Description
	}

	if err := r.DB.Save(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return mapping.MapUserToGraphQL(&user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return false, fmt.Errorf("user not found: %w", err)
	}

	if err := r.DB.Delete(&user).Error; err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	return true, nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	if userID == followerID {
		return false, fmt.Errorf("cannot follow yourself")
	}

	var existing models.Follower
	if err := r.DB.First(&existing, "user_id = ? AND follower_id = ?", userID, followerID).Error; err == nil {
		return false, fmt.Errorf("user %s already following %s", userID, followerID)
	}

	follow := &models.Follower{
		UserID:     uuid.MustParse(userID),
		FollowerID: uuid.MustParse(followerID),
	}

	if err := r.DB.Create(follow).Error; err != nil {
		return false, fmt.Errorf("failed to follow: %w ", err)
	}

	return true, nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string, followerID string) (bool, error) {
	var follow models.Follower
	if err := r.DB.First(&follow, "user_id = ? AND follower_id = ?", userID, followerID).Error; err != nil {
		return false, fmt.Errorf("user %s dont following %s", userID, followerID)
	}

	if err := r.DB.Delete(&follow).Error; err != nil {
		return false, fmt.Errorf("failed to unfollow: %w", err)
	}

	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	group := &models.Group{}

	if err := r.DB.Create(group).Error; err != nil {
		return nil, fmt.Errorf("failed to create group: %w", err)
	}

	var members []models.Member
	for _, userIDStr := range input.MemberIds {
		userID, err := uuid.Parse(userIDStr)
		if err != nil {
			return nil, fmt.Errorf("invalid user ID: %s", userIDStr)
		}

		member := models.Member{
			UserID:  userID,
			GroupID: group.ID,
		}

		if err := r.DB.Create(&member).Error; err != nil {
			return nil, fmt.Errorf("failed to add user %s to group: %w", userIDStr, err)
		}

		members = append(members, member)
	}

	for i := range members {
		if err := r.DB.First(&members[i].User, "id = ?", members[i].UserID).Error; err != nil {
			return nil, fmt.Errorf("failed to load user %s: %w", members[i].UserID, err)
		}
	}

	return mapping.MapGroupToGraphQL(group, members), nil
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var existing models.Member
	if err := r.DB.First(&existing, "user_id = ? AND group_id = ?", userID, groupID).Error; err == nil {
		return false, fmt.Errorf("user already in the group")
	}

	member := &models.Member{
		UserID:  uuid.MustParse(userID),
		GroupID: uuid.MustParse(groupID),
	}

	if err := r.DB.Create(member).Error; err != nil {
		return false, fmt.Errorf("failed to add user to group: %w", err)
	}

	return true, nil
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var membership models.Member
	if err := r.DB.First(&membership, "user_id = ? AND group_id = ?", userID, groupID).Error; err != nil {
		return false, fmt.Errorf("user %s not in group %s", userID, groupID)
	}

	if err := r.DB.Delete(&membership).Error; err != nil {
		return false, fmt.Errorf("failed to remove user from group: %w", err)
	}

	return true, nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	var group models.Group
	if err := r.DB.First(&group, "id = ?", id).Error; err != nil {
		return false, fmt.Errorf("group not found: %w", err)
	}

	if err := r.DB.Delete(&group).Error; err != nil {
		return false, fmt.Errorf("failed to delete group: %w", err)
	}

	return true, nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", id).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}

	var followers []*model.User
	for _, link := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", link.FollowerID).Error; err == nil {
			followers = append(followers, mapping.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", id).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}

	var following []*model.User
	for _, link := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", link.UserID).Error; err == nil {
			following = append(following, mapping.MapUserToGraphQL(&u))
		}
	}

	res := mapping.MapUserToGraphQL(&user)
	res.Followers = followers
	res.Following = following

	return res, nil
}

// UserByNickname is the resolver for the userByNickname field.
func (r *queryResolver) UserByNickname(ctx context.Context, nickname string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "nickname = ?", nickname).Error; err != nil {
		return nil, fmt.Errorf("user not found with nickname %s: %w", nickname, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", user.ID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapping.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", user.ID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapping.MapUserToGraphQL(&u))
		}
	}

	result := mapping.MapUserToGraphQL(&user)
	result.Followers = followers
	result.Following = following

	return result, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	var user models.User
	if err := r.DB.First(&user, "email = ?", email).Error; err != nil {
		return nil, fmt.Errorf("user not found with email %s: %w", email, err)
	}

	//TODO another resolvers

	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", user.ID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapping.MapUserToGraphQL(&u))
		}
	}

	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", user.ID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapping.MapUserToGraphQL(&u))
		}
	}

	result := mapping.MapUserToGraphQL(&user)
	result.Followers = followers
	result.Following = following

	return result, nil
}

// FollowersOf is the resolver for the followersOf field.
func (r *queryResolver) FollowersOf(ctx context.Context, userID string) ([]*model.User, error) {
	var followerLinks []models.Follower
	if err := r.DB.Where("user_id = ?", userID).Find(&followerLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load followers: %w", err)
	}
	var followers []*model.User
	for _, f := range followerLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.FollowerID).Error; err == nil {
			followers = append(followers, mapping.MapUserToGraphQL(&u))
		}
	}

	return followers, nil
}

// FollowingOf is the resolver for the followingOf field.
func (r *queryResolver) FollowingOf(ctx context.Context, userID string) ([]*model.User, error) {
	var followingLinks []models.Follower
	if err := r.DB.Where("follower_id = ?", userID).Find(&followingLinks).Error; err != nil {
		return nil, fmt.Errorf("failed to load following: %w", err)
	}
	var following []*model.User
	for _, f := range followingLinks {
		var u models.User
		if err := r.DB.First(&u, "id = ?", f.UserID).Error; err == nil {
			following = append(following, mapping.MapUserToGraphQL(&u))
		}
	}

	return following, nil
}

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, id string) ([]*model.User, error) {
	var group models.Group
	if err := r.DB.First(&group, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("group not found with id %s: %w", id, err)
	}

	var members []models.Member
	if err := r.DB.Where("group_id = ?", id).Find(&members).Error; err != nil {
		return nil, fmt.Errorf("failed to load members for group %s: %w", id, err)
	}

	var users []*model.User
	for _, member := range members {
		var user models.User
		if err := r.DB.First(&user, "id = ?", member.UserID).Error; err != nil {
			return nil, fmt.Errorf("failed to load user for member %v: %w", member.UserID, err)
		}
		users = append(users, mapping.MapUserToGraphQL(&user))
	}

	return users, nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID string, groupID string) (bool, error) {
	var member models.Member
	if err := r.DB.First(&member, "user_id = ? AND group_id = ?", userID, groupID).Error; err != nil {
		return false, fmt.Errorf("failed to check if user is in group: %w", err)
	}

	return true, nil
}

// GroupsOfUser is the resolver for the groupsOfUser field.
func (r *queryResolver) GroupsOfUser(ctx context.Context, userID string) ([]*model.Group, error) {
	var members []models.Member
	if err := r.DB.Where("user_id = ?", userID).Find(&members).Error; err != nil {
		return nil, fmt.Errorf("failed to find groups for user: %w", err)
	}

	var groups []*model.Group
	for _, member := range members {
		var group models.Group
		if err := r.DB.First(&group, "id = ?", member.GroupID).Error; err != nil {
			return nil, fmt.Errorf("failed to find group: %w", err)
		}

		groups = append(groups, mapping.MapGroupToGraphQL(&group, members))
	}

	return groups, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
