name: ci

on:
  push:
    branches: [ "dev", "main", "ci_setup" ] # ветки в которых настроен ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend services # Чтобы не запускать контейнеры если хоть что-то не собирается
        run: |
          docker build -t content-service ./backend/content-service
          docker build -t feed-service ./backend/feed-service
          docker build -t profile-service ./backend/profile-service

      - name: Build geo-api
        run: |
          docker build -t geo-api ./backend/geo-api

      # TODO: добавить фронтенд когда будет

      - name: Run docker compose
        run: |
          docker compose -f deploy/docker-compose.yml config
          echo " Building up is ok"
      
      - name: Down docker compose
        run: docker compose -f deploy/docker-compose.yml down
