input CreateUserInput {
  nickname: String!
  email: String!
  nick_tag: String!
  profilePicture: String
  description: String
}

input UpdateUserInput {
  nickname: String
  email: String
  nick_tag: String!
  profilePicture: String
  description: String
}

input CreateGroupInput {
  memberIds: [UUID!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(userId: UUID!, input: UpdateUserInput!): User!
  deleteUser(userId: UUID!): Boolean!

  followUser(userId: UUID!, followerId: UUID!): Boolean!
  unfollowUser(userId: UUID!, followerId: UUID!): Boolean!

  createGroup(input: CreateGroupInput!): Group!
  addUserToGroup(userId: UUID!, groupId: UUID!): Boolean!
  removeUserFromGroup(userId: UUID!, groupId: UUID!): Boolean!
  deleteGroup(groupId: UUID!): Boolean!
  requestJoinGroup(groupId: UUID!, userId: UUID!): Boolean!
  acceptJoinToGroup(requestId: UUID!): Boolean!

  changeAccessBookmarks(userId: UUID!, newStatus: UUID!): Boolean!
}

