input CreateUserInput {
  nickname: String!
  email: String!
  profilePicture: String
  description: String
}

input UpdateUserInput {
  nickname: String
  email: String
  profilePicture: String
  description: String
}

input CreateGroupInput {
  memberIds: [ID!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!

  followUser(userId: ID!, followerId: ID!): Boolean!
  unfollowUser(userId: ID!, followerId: ID!): Boolean!

  createGroup(input: CreateGroupInput!): Group!
  addUserToGroup(userId: ID!, groupId: ID!): Boolean!
  removeUserFromGroup(userId: ID!, groupId: ID!): Boolean!
  deleteGroup(id: ID!): Boolean!

  changeAccessBookmarks(userId: ID!, newStatus: ID!): Boolean!
}

