input CreateUserInput {
  userId: UUID!
  nickname: String!
  email: String!
  nick_tag: String!
  profilePicture: String
  description: String
}

input UpdateUserInput {
  userId: UUID!
  nickname: String
  email: String
  nick_tag: String
  profilePicture: String
  description: String
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(userId: UUID!, input: UpdateUserInput!): User!
  deleteUser(userId: UUID!): Boolean!

  followUser(userId: UUID!, followerId: UUID!): Boolean!
  unfollowUser(userId: UUID!, followerId: UUID!): Boolean!

  changeAccessBookmarks(userId: UUID!, newStatus: Int!): Boolean!
}
