type Query {
  userById(userId: ID!): User
  userByNickname(nickname: String!): User
  userByEmail(email: String!): User

  followersOf(userId: ID!): [User!]!
  followingOf(userId: ID!): [User!]!
  followersCount(userId: ID!): Int!
  followingCount(userId: ID!): Int!

  groupById(groupId: ID!): [User!]
  isUserInGroup(userId: ID!, groupId: ID!): Boolean!
  groupsOfUser(userId: ID!): [Group!]!
  requestJoinGroup(groupId: ID!, userId: ID!): Boolean!
  acceptJoinToGroup(requestId: ID!): Boolean!

  getSettingsStatuses: [SettingsStatuses!]!
}
